import type { QSeed } from "./tipos";

const A = "Beneficios Eventuais";

const questoes: QSeed[] = [
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Segundo a LOAS, os benefícios eventuais são:",
    alternativas: [
      { texto: "provisões suplementares e provisórias prestadas aos cidadãos e famílias em virtude de nascimento, morte, situações de vulnerabilidade temporária e calamidade pública.", correta: true },
      { texto: "benefícios permanentes equivalentes a um salário mínimo mensal.", correta: false },
      { texto: "aposentadorias concedidas a pessoas idosas.", correta: false },
      { texto: "transferências condicionadas à frequência escolar.", correta: false },
      { texto: "benefícios contributivos da previdência.", correta: false },
    ],
    explicacao:
      "O art. 22 da LOAS define os benefícios eventuais como provisões suplementares e provisórias prestadas em razão de nascimento, morte, vulnerabilidade temporária e calamidade pública.",
    fonteLegal: "Lei 8.742/1993 (LOAS), art. 22",
    palavrasChave: ["benefícios eventuais", "provisório", "suplementar"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A competência para a concessão e o valor dos benefícios eventuais é, em regra:",
    alternativas: [
      { texto: "dos municípios e do DF, com participação do cofinanciamento estadual e federal.", correta: true },
      { texto: "exclusiva da União.", correta: false },
      { texto: "de entidades privadas com fins lucrativos.", correta: false },
      { texto: "do Poder Judiciário.", correta: false },
      { texto: "do Ministério Público.", correta: false },
    ],
    explicacao:
      "A LOAS estabelece que a concessão e o valor dos benefícios eventuais são definidos pelos municípios e pelo DF, observados critérios e prazos, podendo haver participação estadual e federal no cofinanciamento.",
    fonteLegal: "Lei 8.742/1993, art. 22; Decreto 6.307/2007",
    palavrasChave: ["competência", "município", "DF"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O auxílio-natalidade e o auxílio-funeral são exemplos de:",
    alternativas: [
      { texto: "benefícios eventuais relacionados a nascimento e morte.", correta: true },
      { texto: "benefícios previdenciários contributivos.", correta: false },
      { texto: "serviços de proteção social especial.", correta: false },
      { texto: "programas de transferência condicionada.", correta: false },
      { texto: "benefícios de prestação continuada.", correta: false },
    ],
    explicacao:
      "O auxílio-natalidade (nascimento) e o auxílio-funeral (morte) são as hipóteses clássicas de benefícios eventuais previstas a partir da LOAS e regulamentadas pelo Decreto 6.307/2007.",
    fonteLegal: "Lei 8.742/1993, art. 22; Decreto 6.307/2007",
    palavrasChave: ["auxílio-natalidade", "auxílio-funeral"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A instância responsável por estabelecer critérios e prazos dos benefícios eventuais, no âmbito do controle social, é:",
    alternativas: [
      { texto: "o Conselho de Assistência Social, mediante deliberação.", correta: true },
      { texto: "o Tribunal de Contas.", correta: false },
      { texto: "a Câmara de Vereadores, isoladamente.", correta: false },
      { texto: "uma empresa privada.", correta: false },
      { texto: "o cartório de registro civil.", correta: false },
    ],
    explicacao:
      "Cabe ao Conselho de Assistência Social (do município ou do DF) regulamentar, por deliberação, os critérios e prazos dos benefícios eventuais, observados os parâmetros legais.",
    fonteLegal: "Lei 8.742/1993, art. 22, §1º; Decreto 6.307/2007",
    palavrasChave: ["conselho", "deliberação", "critérios"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Os benefícios eventuais integram organicamente:",
    alternativas: [
      { texto: "as garantias do SUAS, no campo da assistência social.", correta: true },
      { texto: "o regime geral de previdência social.", correta: false },
      { texto: "o sistema tributário nacional.", correta: false },
      { texto: "a política de saúde suplementar.", correta: false },
      { texto: "o sistema financeiro.", correta: false },
    ],
    explicacao:
      "Os benefícios eventuais integram organicamente as garantias do SUAS, sendo prestados no âmbito da política de assistência social.",
    fonteLegal: "Decreto 6.307/2007; LOAS",
    palavrasChave: ["SUAS", "garantias"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O benefício eventual em razão de vulnerabilidade temporária destina-se a:",
    alternativas: [
      { texto: "enfrentar contingências que ocasionem riscos e fragilizem a manutenção do indivíduo e da família.", correta: true },
      { texto: "substituir permanentemente a renda da família.", correta: false },
      { texto: "conceder aposentadoria antecipada.", correta: false },
      { texto: "custear despesas de empresas.", correta: false },
      { texto: "pagar tributos atrasados.", correta: false },
    ],
    explicacao:
      "O benefício por vulnerabilidade temporária visa enfrentar situações de riscos, perdas e danos que comprometem temporariamente a sobrevivência e a manutenção do indivíduo e da família.",
    fonteLegal: "Decreto 6.307/2007, art. 9º",
    palavrasChave: ["vulnerabilidade temporária", "contingência"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O benefício eventual em situação de calamidade pública tem por objetivo:",
    alternativas: [
      { texto: "assegurar a sobrevivência e a reconstrução da autonomia das famílias atingidas.", correta: true },
      { texto: "financiar obras de grande porte.", correta: false },
      { texto: "conceder isenções tributárias a empresas.", correta: false },
      { texto: "substituir o seguro privado.", correta: false },
      { texto: "remunerar servidores públicos.", correta: false },
    ],
    explicacao:
      "Em calamidade pública, o benefício eventual destina-se a garantir a sobrevivência das famílias e indivíduos atingidos, contribuindo para o restabelecimento de suas condições de vida.",
    fonteLegal: "Decreto 6.307/2007, art. 10",
    palavrasChave: ["calamidade pública", "sobrevivência"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "Sobre a forma do benefício eventual, é correto afirmar que pode ser concedido:",
    alternativas: [
      { texto: "em pecúnia (dinheiro) ou em bens de consumo, conforme regulamentação.", correta: true },
      { texto: "exclusivamente em forma de empréstimo.", correta: false },
      { texto: "somente mediante prestação de serviço pela família.", correta: false },
      { texto: "apenas em forma de desconto tributário.", correta: false },
      { texto: "unicamente como vaga em abrigo.", correta: false },
    ],
    explicacao:
      "Os benefícios eventuais podem ser prestados em pecúnia ou em bens de consumo, conforme a regulamentação local, sendo vedado o caráter de empréstimo ou contraprestação.",
    fonteLegal: "Decreto 6.307/2007",
    palavrasChave: ["pecúnia", "bens de consumo"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O acesso aos benefícios eventuais é:",
    alternativas: [
      { texto: "um direito do cidadão, não condicionado a contribuição prévia.", correta: true },
      { texto: "condicionado ao pagamento de contribuições.", correta: false },
      { texto: "restrito a quem possui carteira assinada.", correta: false },
      { texto: "exclusivo de servidores públicos.", correta: false },
      { texto: "dependente de filiação partidária.", correta: false },
    ],
    explicacao:
      "Como benefício assistencial, o acesso é direito do cidadão que dele necessitar, sem exigência de contribuição prévia.",
    fonteLegal: "LOAS; Decreto 6.307/2007",
    palavrasChave: ["direito", "não contributivo"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Os benefícios eventuais NÃO se confundem com:",
    alternativas: [
      { texto: "os benefícios permanentes, como o BPC.", correta: true },
      { texto: "as provisões temporárias de assistência social.", correta: false },
      { texto: "o auxílio-natalidade.", correta: false },
      { texto: "o auxílio-funeral.", correta: false },
      { texto: "as provisões em calamidade pública.", correta: false },
    ],
    explicacao:
      "Os benefícios eventuais têm caráter provisório e suplementar, diferenciando-se de benefícios permanentes como o BPC (que assegura um salário mínimo continuado).",
    fonteLegal: "LOAS, arts. 20 e 22",
    palavrasChave: ["BPC", "permanente", "eventual"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A integração dos benefícios eventuais aos serviços socioassistenciais visa:",
    alternativas: [
      { texto: "articular a provisão material ao acompanhamento e ao acesso a direitos pelas famílias.", correta: true },
      { texto: "substituir os serviços pela mera entrega de bens.", correta: false },
      { texto: "isolar a família da rede de proteção.", correta: false },
      { texto: "vedar o trabalho social com famílias.", correta: false },
      { texto: "eliminar o papel dos CRAS.", correta: false },
    ],
    explicacao:
      "A concessão deve articular-se aos serviços (PAIF/PAEFI), de modo que a provisão material seja acompanhada de trabalho social e do acesso a outros direitos, evitando ações isoladas e assistencialistas.",
    fonteLegal: "Decreto 6.307/2007; PNAS/2004",
    palavrasChave: ["integração", "serviços", "acompanhamento"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O custeio dos benefícios eventuais ocorre por meio de:",
    alternativas: [
      { texto: "recursos dos fundos de assistência social, sob controle dos conselhos.", correta: true },
      { texto: "contribuições previdenciárias.", correta: false },
      { texto: "tarifas pagas pelos beneficiários.", correta: false },
      { texto: "doações obrigatórias de empresas.", correta: false },
      { texto: "empréstimos bancários das famílias.", correta: false },
    ],
    explicacao:
      "Os benefícios eventuais são custeados com recursos dos fundos de assistência social (municipal/DF), com possível cofinanciamento de outras esferas, sob controle dos conselhos.",
    fonteLegal: "LOAS; Decreto 6.307/2007",
    palavrasChave: ["fundo", "custeio", "cofinanciamento"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "É vedado, na prestação dos benefícios eventuais:",
    alternativas: [
      { texto: "a exigência de comprovação vexatória de necessidade e o condicionamento a contrapartidas indevidas.", correta: true },
      { texto: "a articulação com os serviços socioassistenciais.", correta: false },
      { texto: "a concessão a famílias em vulnerabilidade.", correta: false },
      { texto: "a deliberação pelo conselho de assistência social.", correta: false },
      { texto: "o custeio pelo fundo de assistência social.", correta: false },
    ],
    explicacao:
      "É vedada a comprovação vexatória da necessidade, em respeito à dignidade do usuário (princípio da LOAS); o acesso não pode ser condicionado a contrapartidas indevidas.",
    fonteLegal: "LOAS, art. 4º; Decreto 6.307/2007",
    palavrasChave: ["vedação", "comprovação vexatória", "dignidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "No Distrito Federal, a regulamentação dos benefícios eventuais compete:",
    alternativas: [
      { texto: "ao DF (que acumula competências estadual e municipal), com deliberação do conselho distrital.", correta: true },
      { texto: "a municípios vizinhos de Goiás.", correta: false },
      { texto: "exclusivamente à União.", correta: false },
      { texto: "a entidades privadas.", correta: false },
      { texto: "ao Poder Judiciário.", correta: false },
    ],
    explicacao:
      "Por acumular competências estaduais e municipais, o DF regulamenta seus benefícios eventuais, com deliberação do Conselho de Assistência Social do DF, observados os parâmetros legais federais.",
    fonteLegal: "LOAS; Decreto 6.307/2007; CF/1988, art. 32",
    palavrasChave: ["Distrito Federal", "regulamentação", "conselho"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A natureza dos benefícios eventuais é:",
    alternativas: [
      { texto: "temporária e complementar às demais ações da assistência social.", correta: true },
      { texto: "permanente e substitutiva da renda.", correta: false },
      { texto: "contributiva e atuarial.", correta: false },
      { texto: "exclusivamente em forma de serviço.", correta: false },
      { texto: "vinculada ao tempo de contribuição.", correta: false },
    ],
    explicacao:
      "Os benefícios eventuais têm natureza temporária e complementar (suplementar), atuando em situações específicas, sem substituir de forma permanente a renda das famílias.",
    fonteLegal: "LOAS, art. 22; Decreto 6.307/2007",
    palavrasChave: ["temporário", "complementar"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A concessão de benefícios eventuais deve observar o princípio da:",
    alternativas: [
      { texto: "igualdade de acesso, sem discriminação, e respeito à dignidade do usuário.", correta: true },
      { texto: "seletividade por capacidade contributiva.", correta: false },
      { texto: "exclusividade para servidores.", correta: false },
      { texto: "primazia do lucro.", correta: false },
      { texto: "vedação ao controle social.", correta: false },
    ],
    explicacao:
      "A concessão observa os princípios da assistência social: igualdade de acesso, não discriminação e respeito à dignidade e à autonomia do usuário.",
    fonteLegal: "LOAS, art. 4º; Decreto 6.307/2007",
    palavrasChave: ["igualdade", "dignidade", "não discriminação"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O auxílio por morte (auxílio-funeral) pode cobrir, conforme regulamentação:",
    alternativas: [
      { texto: "despesas de urna, traslado, sepultamento e outras necessárias decorrentes do óbito.", correta: true },
      { texto: "apenas o pagamento de tributos.", correta: false },
      { texto: "a aquisição de imóveis pela família.", correta: false },
      { texto: "exclusivamente despesas médicas anteriores.", correta: false },
      { texto: "a compra de veículos.", correta: false },
    ],
    explicacao:
      "O auxílio por morte pode custear despesas como urna funerária, traslado, sepultamento e outras decorrentes do óbito, conforme regulamentação local.",
    fonteLegal: "Decreto 6.307/2007",
    palavrasChave: ["auxílio-funeral", "óbito", "despesas"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O auxílio por nascimento (auxílio-natalidade) destina-se a atender:",
    alternativas: [
      { texto: "necessidades do recém-nascido e da família, como enxoval e itens essenciais.", correta: true },
      { texto: "o pagamento de impostos da família.", correta: false },
      { texto: "a compra de bens de luxo.", correta: false },
      { texto: "despesas com veículos.", correta: false },
      { texto: "a quitação de empréstimos bancários.", correta: false },
    ],
    explicacao:
      "O auxílio-natalidade visa atender as necessidades do recém-nascido e da família (como enxoval e itens essenciais), conforme regulamentação do ente.",
    fonteLegal: "Decreto 6.307/2007",
    palavrasChave: ["auxílio-natalidade", "recém-nascido", "enxoval"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A ausência de regulamentação local dos critérios dos benefícios eventuais:",
    alternativas: [
      { texto: "não afasta o dever do ente de prestá-los, observados os parâmetros legais.", correta: true },
      { texto: "extingue o direito dos cidadãos.", correta: false },
      { texto: "transfere a competência para empresas privadas.", correta: false },
      { texto: "torna o benefício contributivo.", correta: false },
      { texto: "elimina o papel do conselho.", correta: false },
    ],
    explicacao:
      "Os benefícios eventuais são direito previsto em lei; a regulamentação detalha critérios e prazos, mas sua ausência não afasta o dever do ente de prover a proteção, observados os parâmetros da LOAS.",
    fonteLegal: "LOAS, art. 22; Decreto 6.307/2007",
    palavrasChave: ["regulamentação", "direito", "dever do ente"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A diferença entre benefício eventual e serviço socioassistencial é que:",
    alternativas: [
      { texto: "o benefício é uma provisão (em pecúnia ou bens) para contingências específicas; o serviço é uma atividade continuada de atendimento.", correta: true },
      { texto: "ambos são atividades continuadas idênticas.", correta: false },
      { texto: "o serviço é sempre uma provisão financeira.", correta: false },
      { texto: "o benefício eventual é um serviço de saúde.", correta: false },
      { texto: "não há qualquer diferença.", correta: false },
    ],
    explicacao:
      "O benefício eventual é uma provisão pontual (pecúnia/bens) para contingências; o serviço socioassistencial (como PAIF e SCFV) é atividade continuada de atendimento, acompanhamento e fortalecimento de vínculos.",
    fonteLegal: "LOAS; Tipificação Nacional; Decreto 6.307/2007",
    palavrasChave: ["benefício", "serviço", "diferença"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Os benefícios eventuais expressam a função de proteção social da assistência ao:",
    alternativas: [
      { texto: "responder a situações de risco e contingências da vida das famílias.", correta: true },
      { texto: "substituir a previdência social.", correta: false },
      { texto: "financiar a atividade econômica.", correta: false },
      { texto: "arrecadar tributos.", correta: false },
      { texto: "regular o mercado de trabalho.", correta: false },
    ],
    explicacao:
      "Os benefícios eventuais materializam a proteção social ao responder a riscos e contingências (nascimento, morte, vulnerabilidade temporária, calamidade) que afetam as famílias.",
    fonteLegal: "LOAS, art. 22; PNAS/2004",
    palavrasChave: ["proteção social", "contingências"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A prestação dos benefícios eventuais pressupõe a identificação das necessidades por meio de:",
    alternativas: [
      { texto: "atendimento e avaliação técnica realizados pela equipe da assistência social.", correta: true },
      { texto: "decisão automática sem qualquer avaliação.", correta: false },
      { texto: "análise de capacidade contributiva.", correta: false },
      { texto: "indicação política.", correta: false },
      { texto: "sorteio entre as famílias.", correta: false },
    ],
    explicacao:
      "A concessão pressupõe o atendimento e a avaliação técnica da equipe de assistência social, que identifica a necessidade e articula o benefício ao acompanhamento da família.",
    fonteLegal: "Decreto 6.307/2007; PNAS/2004",
    palavrasChave: ["avaliação técnica", "equipe", "necessidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A previsão de benefícios eventuais no orçamento e no plano de assistência social é importante porque:",
    alternativas: [
      { texto: "garante recursos e planejamento para o atendimento das contingências das famílias.", correta: true },
      { texto: "impede a concessão dos benefícios.", correta: false },
      { texto: "transfere a responsabilidade às famílias.", correta: false },
      { texto: "elimina o controle social.", correta: false },
      { texto: "torna o benefício contributivo.", correta: false },
    ],
    explicacao:
      "A previsão orçamentária e no plano de assistência social assegura recursos e planejamento para a oferta regular dos benefícios eventuais, evitando descontinuidades.",
    fonteLegal: "LOAS; NOB-SUAS; Decreto 6.307/2007",
    palavrasChave: ["orçamento", "planejamento", "plano"],
  },
];

export default questoes;
