import type { QSeed } from "./tipos";

const A = "Cartao Gas";

const questoes: QSeed[] = [
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O programa Cartão Gás, no Distrito Federal, tem como finalidade principal:",
    alternativas: [
      { texto: "auxiliar financeiramente famílias de baixa renda na aquisição de gás de cozinha (GLP).", correta: true },
      { texto: "custear o transporte público das famílias.", correta: false },
      { texto: "pagar contas de energia elétrica.", correta: false },
      { texto: "financiar a compra de medicamentos.", correta: false },
      { texto: "subsidiar a compra de veículos.", correta: false },
    ],
    explicacao:
      "O Cartão Gás é um benefício de transferência de renda do GDF voltado a auxiliar famílias de baixa renda na compra do gás de cozinha (GLP), atuando na segurança alimentar e na proteção social.",
    fonteLegal: "Programa Cartão Gás (GDF/SEDES)",
    palavrasChave: ["GLP", "gás de cozinha", "transferência de renda"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O público-alvo do Cartão Gás é composto, prioritariamente, por:",
    alternativas: [
      { texto: "famílias de baixa renda em situação de vulnerabilidade social.", correta: true },
      { texto: "famílias de alta renda.", correta: false },
      { texto: "apenas servidores públicos.", correta: false },
      { texto: "exclusivamente empresas.", correta: false },
      { texto: "somente turistas em trânsito.", correta: false },
    ],
    explicacao:
      "O benefício destina-se a famílias de baixa renda em situação de vulnerabilidade social, em regra inscritas no Cadastro Único.",
    fonteLegal: "Programa Cartão Gás (GDF/SEDES)",
    palavrasChave: ["baixa renda", "vulnerabilidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A seleção dos beneficiários do Cartão Gás baseia-se, em regra, em informações do:",
    alternativas: [
      { texto: "Cadastro Único para Programas Sociais (CadÚnico).", correta: true },
      { texto: "cadastro de contribuintes do ICMS.", correta: false },
      { texto: "registro de veículos do Detran.", correta: false },
      { texto: "cadastro de empresas da Junta Comercial.", correta: false },
      { texto: "cadastro eleitoral.", correta: false },
    ],
    explicacao:
      "A identificação e a seleção das famílias beneficiárias têm como base o Cadastro Único, instrumento que caracteriza socioeconomicamente as famílias de baixa renda.",
    fonteLegal: "Programa Cartão Gás; Cadastro Único",
    palavrasChave: ["CadÚnico", "seleção"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O Cartão Gás insere-se entre as ações de:",
    alternativas: [
      { texto: "proteção social e segurança alimentar do Plano DF Social.", correta: true },
      { texto: "política tributária do DF.", correta: false },
      { texto: "regulação do trânsito.", correta: false },
      { texto: "gestão de pessoal da administração.", correta: false },
      { texto: "política industrial.", correta: false },
    ],
    explicacao:
      "O Cartão Gás integra a rede de proteção social e de segurança alimentar e nutricional articulada pelo Plano DF Social, sob gestão da SEDES.",
    fonteLegal: "Programa Cartão Gás; Plano DF Social",
    palavrasChave: ["proteção social", "segurança alimentar"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O órgão gestor do Cartão Gás no DF é, prioritariamente:",
    alternativas: [
      { texto: "a Secretaria de Desenvolvimento Social (SEDES).", correta: true },
      { texto: "a Secretaria de Fazenda.", correta: false },
      { texto: "a Secretaria de Transportes.", correta: false },
      { texto: "a Polícia Militar.", correta: false },
      { texto: "o Tribunal de Justiça.", correta: false },
    ],
    explicacao:
      "A gestão do programa cabe à SEDES, órgão responsável pela política de desenvolvimento e assistência social do Distrito Federal.",
    fonteLegal: "Programa Cartão Gás (GDF/SEDES)",
    palavrasChave: ["SEDES", "gestão"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A natureza do benefício concedido pelo Cartão Gás é:",
    alternativas: [
      { texto: "transferência de renda destinada a uma finalidade específica (aquisição de GLP).", correta: true },
      { texto: "empréstimo a ser quitado pela família.", correta: false },
      { texto: "doação de bens duráveis.", correta: false },
      { texto: "benefício previdenciário contributivo.", correta: false },
      { texto: "isenção tributária.", correta: false },
    ],
    explicacao:
      "Trata-se de transferência de renda com finalidade específica: auxiliar na aquisição do gás de cozinha, sem caráter de empréstimo ou de benefício contributivo.",
    fonteLegal: "Programa Cartão Gás (GDF/SEDES)",
    palavrasChave: ["transferência de renda", "finalidade específica"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A relação entre o Cartão Gás e a segurança alimentar e nutricional é direta porque:",
    alternativas: [
      { texto: "o acesso ao gás de cozinha é condição para o preparo de alimentos no domicílio.", correta: true },
      { texto: "o gás de cozinha é um alimento.", correta: false },
      { texto: "o programa distribui cestas básicas.", correta: false },
      { texto: "o benefício substitui a renda familiar integralmente.", correta: false },
      { texto: "não há relação com a alimentação.", correta: false },
    ],
    explicacao:
      "O gás de cozinha viabiliza o preparo dos alimentos em casa; garantir seu acesso a famílias vulneráveis contribui diretamente para a segurança alimentar e nutricional.",
    fonteLegal: "Programa Cartão Gás; LOSAN",
    palavrasChave: ["segurança alimentar", "preparo de alimentos"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A atualização cadastral das famílias é importante para o Cartão Gás porque:",
    alternativas: [
      { texto: "mantém a focalização do benefício e a fidedignidade das informações de elegibilidade.", correta: true },
      { texto: "aumenta a carga tributária da família.", correta: false },
      { texto: "elimina o controle social do programa.", correta: false },
      { texto: "é irrelevante para a concessão.", correta: false },
      { texto: "serve apenas para fins estatísticos.", correta: false },
    ],
    explicacao:
      "A atualização periódica do Cadastro Único garante que as informações reflitam a realidade das famílias, preservando a focalização e a correta concessão do benefício.",
    fonteLegal: "Programa Cartão Gás; Cadastro Único",
    palavrasChave: ["atualização cadastral", "focalização"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O Cartão Gás caracteriza-se como benefício:",
    alternativas: [
      { texto: "não contributivo, custeado por recursos públicos do DF.", correta: true },
      { texto: "contributivo, financiado por contribuições dos beneficiários.", correta: false },
      { texto: "pago por empresas privadas.", correta: false },
      { texto: "custeado por organismos internacionais.", correta: false },
      { texto: "vinculado ao tempo de contribuição.", correta: false },
    ],
    explicacao:
      "Como benefício assistencial, o Cartão Gás é não contributivo, custeado com recursos públicos do Distrito Federal.",
    fonteLegal: "Programa Cartão Gás (GDF/SEDES)",
    palavrasChave: ["não contributivo", "recursos públicos"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A integração do Cartão Gás com a rede do SUAS permite que:",
    alternativas: [
      { texto: "as famílias sejam identificadas, encaminhadas e acompanhadas pelos CRAS.", correta: true },
      { texto: "o benefício seja concedido sem qualquer critério.", correta: false },
      { texto: "os CRAS sejam substituídos por empresas.", correta: false },
      { texto: "as famílias percam acesso a outros programas.", correta: false },
      { texto: "o acompanhamento familiar seja proibido.", correta: false },
    ],
    explicacao:
      "A rede do SUAS, em especial os CRAS, contribui para identificar, encaminhar e acompanhar as famílias beneficiárias, integrando o benefício à proteção social básica.",
    fonteLegal: "Programa Cartão Gás; PNAS/2004",
    palavrasChave: ["SUAS", "CRAS", "acompanhamento"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Um critério comum de elegibilidade para benefícios como o Cartão Gás é:",
    alternativas: [
      { texto: "a renda familiar per capita dentro de um limite definido pelo programa.", correta: true },
      { texto: "a posse de imóveis de alto padrão.", correta: false },
      { texto: "a titularidade de empresa de grande porte.", correta: false },
      { texto: "o exercício de cargo público de alto escalão.", correta: false },
      { texto: "a renda elevada.", correta: false },
    ],
    explicacao:
      "Programas de transferência de renda como o Cartão Gás costumam adotar critério de renda familiar per capita (limite de baixa renda), aferida pelo Cadastro Único.",
    fonteLegal: "Programa Cartão Gás; Cadastro Único",
    palavrasChave: ["renda per capita", "elegibilidade"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O Cartão Gás contribui para reduzir o risco de:",
    alternativas: [
      { texto: "uso de meios inadequados e perigosos para cozinhar, por falta de acesso ao GLP.", correta: true },
      { texto: "aumento da renda das famílias de alta renda.", correta: false },
      { texto: "redução do acesso à educação.", correta: false },
      { texto: "elevação da arrecadação tributária.", correta: false },
      { texto: "diminuição da oferta de serviços de saúde.", correta: false },
    ],
    explicacao:
      "Sem acesso ao gás de cozinha, famílias vulneráveis podem recorrer a meios inadequados e perigosos (como lenha ou álcool) para cozinhar; o benefício reduz esse risco e melhora a segurança alimentar.",
    fonteLegal: "Programa Cartão Gás (GDF/SEDES)",
    palavrasChave: ["risco", "GLP", "segurança"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A concessão do Cartão Gás, por ser benefício público, sujeita-se a:",
    alternativas: [
      { texto: "critérios objetivos, transparência e controle social.", correta: true },
      { texto: "decisão discricionária e sigilosa do gestor.", correta: false },
      { texto: "ausência de qualquer critério.", correta: false },
      { texto: "regras definidas por empresas privadas.", correta: false },
      { texto: "vedação ao controle externo.", correta: false },
    ],
    explicacao:
      "Como política pública, a concessão observa critérios objetivos e princípios de transparência e controle social, sujeitando-se à fiscalização dos órgãos de controle e dos conselhos.",
    fonteLegal: "Programa Cartão Gás; princípios da administração pública",
    palavrasChave: ["transparência", "controle social", "critérios"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A articulação do Cartão Gás com outros benefícios (como o Prato Cheio) evidencia a lógica de:",
    alternativas: [
      { texto: "complementaridade das ações de proteção social e segurança alimentar.", correta: true },
      { texto: "concorrência entre programas, que se excluem mutuamente.", correta: false },
      { texto: "substituição da assistência social pela previdência.", correta: false },
      { texto: "fragmentação proposital das políticas.", correta: false },
      { texto: "vedação ao acúmulo de qualquer apoio.", correta: false },
    ],
    explicacao:
      "Os programas se complementam dentro da rede de proteção: o Cartão Gás (acesso ao GLP) e o Prato Cheio (alimentação) atuam de forma articulada para enfrentar a insegurança alimentar.",
    fonteLegal: "Programa Cartão Gás; Plano DF Social",
    palavrasChave: ["complementaridade", "rede de proteção"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A operacionalização do benefício por meio de cartão magnético tem como vantagem:",
    alternativas: [
      { texto: "facilitar o uso, o controle e a transparência da transferência de renda.", correta: true },
      { texto: "impedir o acesso da família ao benefício.", correta: false },
      { texto: "elevar custos sem qualquer benefício.", correta: false },
      { texto: "tornar o benefício sigiloso para a gestão.", correta: false },
      { texto: "substituir o Cadastro Único.", correta: false },
    ],
    explicacao:
      "O uso de cartão magnético facilita o acesso da família ao recurso, melhora o controle dos gastos e amplia a transparência da gestão do benefício.",
    fonteLegal: "Programa Cartão Gás (GDF/SEDES)",
    palavrasChave: ["cartão magnético", "controle"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A revisão periódica dos benefícios concedidos pelo Cartão Gás visa:",
    alternativas: [
      { texto: "verificar a permanência das condições de elegibilidade das famílias.", correta: true },
      { texto: "punir as famílias beneficiárias.", correta: false },
      { texto: "encerrar definitivamente o programa.", correta: false },
      { texto: "aumentar a renda das famílias de alta renda.", correta: false },
      { texto: "eliminar o Cadastro Único.", correta: false },
    ],
    explicacao:
      "A revisão periódica assegura que apenas as famílias que continuam atendendo aos critérios permaneçam no programa, mantendo a focalização e a boa aplicação dos recursos.",
    fonteLegal: "Programa Cartão Gás; Cadastro Único",
    palavrasChave: ["revisão", "elegibilidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Em relação ao orçamento, o Cartão Gás depende de:",
    alternativas: [
      { texto: "disponibilidade orçamentária e financeira definida nas leis orçamentárias do DF.", correta: true },
      { texto: "contribuições obrigatórias das famílias.", correta: false },
      { texto: "doações exclusivas de empresas.", correta: false },
      { texto: "recursos do orçamento da União apenas.", correta: false },
      { texto: "arrecadação de multas de trânsito.", correta: false },
    ],
    explicacao:
      "Por ser benefício custeado pelo DF, sua concessão depende da disponibilidade orçamentária e financeira prevista nas leis orçamentárias distritais.",
    fonteLegal: "Programa Cartão Gás; LDO/LOA do DF",
    palavrasChave: ["orçamento", "disponibilidade financeira"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O Cartão Gás é um exemplo de política pública focada em:",
    alternativas: [
      { texto: "garantir um direito social básico relacionado à alimentação e à dignidade.", correta: true },
      { texto: "aumentar a desigualdade social.", correta: false },
      { texto: "beneficiar prioritariamente quem tem alta renda.", correta: false },
      { texto: "restringir o acesso a direitos.", correta: false },
      { texto: "substituir a política de saúde.", correta: false },
    ],
    explicacao:
      "O benefício materializa um direito social relacionado à alimentação e à dignidade humana, no âmbito da proteção social do DF.",
    fonteLegal: "Programa Cartão Gás; CF/1988, art. 6º",
    palavrasChave: ["direito social", "dignidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O acompanhamento das famílias beneficiárias do Cartão Gás pelos CRAS pode contribuir para:",
    alternativas: [
      { texto: "o acesso a outros serviços e a superação das vulnerabilidades, na lógica da proteção integral.", correta: true },
      { texto: "o isolamento das famílias da rede de proteção.", correta: false },
      { texto: "a exclusão das famílias de outros programas.", correta: false },
      { texto: "a redução dos direitos das famílias.", correta: false },
      { texto: "o fim do trabalho social com famílias.", correta: false },
    ],
    explicacao:
      "O acompanhamento pelos CRAS conecta as famílias a outros serviços e benefícios, favorecendo a proteção integral e a superação das vulnerabilidades, para além do benefício pontual.",
    fonteLegal: "Programa Cartão Gás; PNAS/2004",
    palavrasChave: ["CRAS", "proteção integral"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A focalização do Cartão Gás, em comparação com subsídios universais ao GLP, tende a:",
    alternativas: [
      { texto: "concentrar o apoio nas famílias mais pobres, otimizando o uso dos recursos públicos.", correta: true },
      { texto: "beneficiar igualmente todas as faixas de renda.", correta: false },
      { texto: "excluir as famílias de baixa renda.", correta: false },
      { texto: "ampliar o gasto sem critério.", correta: false },
      { texto: "eliminar a necessidade de cadastro.", correta: false },
    ],
    explicacao:
      "Ao focalizar nas famílias de baixa renda (via CadÚnico), o programa direciona melhor os recursos do que subsídios universais, que beneficiam também quem não necessita.",
    fonteLegal: "Programa Cartão Gás (GDF/SEDES)",
    palavrasChave: ["focalização", "eficiência", "recursos públicos"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A finalidade social do Cartão Gás alinha-se ao objetivo constitucional de:",
    alternativas: [
      { texto: "erradicar a pobreza e reduzir as desigualdades sociais.", correta: true },
      { texto: "concentrar renda.", correta: false },
      { texto: "ampliar privilégios de alta renda.", correta: false },
      { texto: "restringir direitos sociais.", correta: false },
      { texto: "reduzir a proteção social.", correta: false },
    ],
    explicacao:
      "O programa contribui para o objetivo fundamental da República de erradicar a pobreza e reduzir as desigualdades sociais (art. 3º, III, da CF).",
    fonteLegal: "Programa Cartão Gás; CF/1988, art. 3º",
    palavrasChave: ["erradicar pobreza", "desigualdades"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Caso uma família supere a situação de vulnerabilidade e a renda ultrapasse o limite do programa, espera-se que:",
    alternativas: [
      { texto: "o benefício seja revisto, podendo ser encerrado conforme os critérios de elegibilidade.", correta: true },
      { texto: "o benefício seja mantido permanentemente, sem revisão.", correta: false },
      { texto: "a família seja punida criminalmente.", correta: false },
      { texto: "a família receba benefício em dobro.", correta: false },
      { texto: "todos os benefícios do DF sejam cancelados.", correta: false },
    ],
    explicacao:
      "Os benefícios focalizados são revistos conforme a evolução da situação das famílias; superada a condição de elegibilidade, o benefício pode ser encerrado, liberando recursos para quem ainda necessita.",
    fonteLegal: "Programa Cartão Gás; Cadastro Único",
    palavrasChave: ["revisão", "elegibilidade", "desligamento"],
  },
];

export default questoes;
