import type { QSeed } from "./tipos";

const A = "Cartao Prato Cheio";

const questoes: QSeed[] = [
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O Cartão Prato Cheio, no Distrito Federal, tem por finalidade:",
    alternativas: [
      { texto: "conceder benefício financeiro para a aquisição de alimentos por famílias em vulnerabilidade.", correta: true },
      { texto: "subsidiar a compra de gás de cozinha.", correta: false },
      { texto: "pagar o transporte público das famílias.", correta: false },
      { texto: "financiar a aquisição de medicamentos.", correta: false },
      { texto: "custear despesas com energia elétrica.", correta: false },
    ],
    explicacao:
      "O Cartão Prato Cheio é um programa de segurança alimentar e nutricional do DF que concede benefício financeiro destinado à compra de alimentos por famílias em situação de insegurança alimentar e vulnerabilidade social.",
    fonteLegal: "Programa Cartão Prato Cheio (GDF/SEDES)",
    palavrasChave: ["alimentos", "segurança alimentar", "transferência de renda"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O público-alvo do Cartão Prato Cheio é composto por:",
    alternativas: [
      { texto: "famílias em situação de insegurança alimentar e vulnerabilidade social.", correta: true },
      { texto: "famílias de alta renda.", correta: false },
      { texto: "apenas grandes produtores rurais.", correta: false },
      { texto: "exclusivamente servidores públicos.", correta: false },
      { texto: "somente empresas do setor alimentício.", correta: false },
    ],
    explicacao:
      "O programa destina-se a famílias em insegurança alimentar e vulnerabilidade social, em regra identificadas pelo Cadastro Único.",
    fonteLegal: "Programa Cartão Prato Cheio (GDF/SEDES)",
    palavrasChave: ["insegurança alimentar", "vulnerabilidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O Cartão Prato Cheio integra a política de:",
    alternativas: [
      { texto: "segurança alimentar e nutricional e de proteção social do DF.", correta: true },
      { texto: "regulação do transporte.", correta: false },
      { texto: "gestão de pessoal do GDF.", correta: false },
      { texto: "arrecadação tributária.", correta: false },
      { texto: "planejamento urbano.", correta: false },
    ],
    explicacao:
      "O programa integra a política de segurança alimentar e nutricional e a rede de proteção social do DF, articulada pelo Plano DF Social e gerida pela SEDES.",
    fonteLegal: "Programa Cartão Prato Cheio; Plano DF Social; LOSAN",
    palavrasChave: ["SAN", "proteção social"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A seleção de beneficiários do Cartão Prato Cheio apoia-se, em regra, no:",
    alternativas: [
      { texto: "Cadastro Único para Programas Sociais.", correta: true },
      { texto: "cadastro de contribuintes do ISS.", correta: false },
      { texto: "registro nacional de veículos.", correta: false },
      { texto: "cadastro de empresas exportadoras.", correta: false },
      { texto: "cadastro de obras públicas.", correta: false },
    ],
    explicacao:
      "Como nos demais programas sociais, a identificação e a seleção das famílias têm como base o Cadastro Único.",
    fonteLegal: "Programa Cartão Prato Cheio; Cadastro Único",
    palavrasChave: ["CadÚnico", "seleção"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O benefício do Cartão Prato Cheio é, em regra, utilizado para:",
    alternativas: [
      { texto: "a compra de gêneros alimentícios em estabelecimentos credenciados.", correta: true },
      { texto: "o saque irrestrito em espécie para qualquer finalidade.", correta: false },
      { texto: "a compra de bens de luxo.", correta: false },
      { texto: "o pagamento de tributos.", correta: false },
      { texto: "a aquisição de veículos.", correta: false },
    ],
    explicacao:
      "O cartão é destinado à compra de alimentos, geralmente em estabelecimentos credenciados, reforçando a finalidade de segurança alimentar do benefício.",
    fonteLegal: "Programa Cartão Prato Cheio (GDF/SEDES)",
    palavrasChave: ["gêneros alimentícios", "credenciados"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "O conceito de segurança alimentar e nutricional (SAN), que fundamenta o Prato Cheio, pressupõe:",
    alternativas: [
      { texto: "o acesso regular e permanente a alimentos de qualidade, em quantidade suficiente, sem comprometer outras necessidades essenciais.", correta: true },
      { texto: "o fornecimento de alimentos apenas em situações de calamidade.", correta: false },
      { texto: "a distribuição de alimentos sem qualquer critério.", correta: false },
      { texto: "a vedação ao acesso a alimentos básicos.", correta: false },
      { texto: "o estímulo ao desperdício de alimentos.", correta: false },
    ],
    explicacao:
      "A LOSAN define SAN como o direito de todos ao acesso regular e permanente a alimentos de qualidade, em quantidade suficiente, sem comprometer o acesso a outras necessidades essenciais, respeitada a diversidade cultural.",
    fonteLegal: "LOSAN (Lei 11.346/2006); Programa Prato Cheio",
    palavrasChave: ["SAN", "acesso regular", "qualidade"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O órgão gestor do Cartão Prato Cheio no DF é:",
    alternativas: [
      { texto: "a Secretaria de Desenvolvimento Social (SEDES).", correta: true },
      { texto: "a Secretaria de Educação.", correta: false },
      { texto: "a Secretaria de Fazenda.", correta: false },
      { texto: "a Defensoria Pública.", correta: false },
      { texto: "o Tribunal de Contas.", correta: false },
    ],
    explicacao:
      "A gestão do programa cabe à SEDES, responsável pela política de desenvolvimento e assistência social do DF.",
    fonteLegal: "Programa Cartão Prato Cheio (GDF/SEDES)",
    palavrasChave: ["SEDES", "gestão"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A natureza do Cartão Prato Cheio como benefício é:",
    alternativas: [
      { texto: "transferência de renda não contributiva, com finalidade de alimentação.", correta: true },
      { texto: "benefício previdenciário.", correta: false },
      { texto: "empréstimo consignado.", correta: false },
      { texto: "isenção fiscal.", correta: false },
      { texto: "doação de imóveis.", correta: false },
    ],
    explicacao:
      "É uma transferência de renda de natureza assistencial (não contributiva), com finalidade específica de garantir o acesso a alimentos.",
    fonteLegal: "Programa Cartão Prato Cheio (GDF/SEDES)",
    palavrasChave: ["não contributivo", "transferência de renda"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A relação do Cartão Prato Cheio com a economia local pode incluir:",
    alternativas: [
      { texto: "o estímulo ao comércio de alimentos por meio dos estabelecimentos credenciados.", correta: true },
      { texto: "o fechamento do comércio local.", correta: false },
      { texto: "a vedação ao uso em mercados.", correta: false },
      { texto: "a substituição do comércio por importações.", correta: false },
      { texto: "a proibição de credenciamento de lojas.", correta: false },
    ],
    explicacao:
      "Ao direcionar a compra de alimentos a estabelecimentos credenciados, o programa também movimenta a economia local, além de garantir a segurança alimentar das famílias.",
    fonteLegal: "Programa Cartão Prato Cheio (GDF/SEDES)",
    palavrasChave: ["economia local", "credenciamento"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O Cartão Prato Cheio contribui diretamente para:",
    alternativas: [
      { texto: "o combate à fome e à insegurança alimentar.", correta: true },
      { texto: "o aumento da concentração de renda.", correta: false },
      { texto: "a redução do acesso a alimentos.", correta: false },
      { texto: "a elevação da carga tributária das famílias pobres.", correta: false },
      { texto: "a restrição de direitos sociais.", correta: false },
    ],
    explicacao:
      "A finalidade central do programa é combater a fome e a insegurança alimentar, garantindo o acesso a alimentos às famílias vulneráveis.",
    fonteLegal: "Programa Cartão Prato Cheio (GDF/SEDES)",
    palavrasChave: ["combate à fome", "insegurança alimentar"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A integração do Prato Cheio com a rede do SUAS favorece:",
    alternativas: [
      { texto: "o acompanhamento das famílias e o acesso a outros serviços e benefícios.", correta: true },
      { texto: "o isolamento das famílias.", correta: false },
      { texto: "a substituição dos CRAS por empresas.", correta: false },
      { texto: "a exclusão das famílias da proteção social.", correta: false },
      { texto: "o fim do acompanhamento familiar.", correta: false },
    ],
    explicacao:
      "A rede do SUAS (CRAS/CREAS) acompanha as famílias beneficiárias, conectando-as a outros serviços e benefícios, na lógica da proteção integral.",
    fonteLegal: "Programa Cartão Prato Cheio; PNAS/2004",
    palavrasChave: ["SUAS", "acompanhamento", "proteção integral"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A focalização do Cartão Prato Cheio por critérios de renda objetiva:",
    alternativas: [
      { texto: "priorizar as famílias em maior situação de pobreza e insegurança alimentar.", correta: true },
      { texto: "beneficiar famílias de alta renda.", correta: false },
      { texto: "distribuir o benefício aleatoriamente.", correta: false },
      { texto: "excluir as famílias mais pobres.", correta: false },
      { texto: "condicionar o acesso à contribuição.", correta: false },
    ],
    explicacao:
      "A focalização por renda (via CadÚnico) prioriza as famílias mais pobres e em maior insegurança alimentar, otimizando o uso dos recursos públicos.",
    fonteLegal: "Programa Cartão Prato Cheio; Cadastro Único",
    palavrasChave: ["focalização", "renda"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A diferença essencial entre o Cartão Prato Cheio e o restaurante comunitário, ambos de SAN, é que:",
    alternativas: [
      { texto: "o Prato Cheio é transferência de renda para compra de alimentos; o restaurante comunitário oferta refeições prontas a preço acessível.", correta: true },
      { texto: "ambos distribuem gás de cozinha.", correta: false },
      { texto: "ambos são benefícios previdenciários.", correta: false },
      { texto: "o Prato Cheio oferta refeições prontas e o restaurante transfere renda.", correta: false },
      { texto: "nenhum dos dois se relaciona à alimentação.", correta: false },
    ],
    explicacao:
      "São ações complementares de SAN: o Prato Cheio repassa recursos para a família comprar alimentos; o restaurante comunitário fornece refeições prontas e nutritivas a preço subsidiado.",
    fonteLegal: "Programas de SAN do DF (GDF/SEDES)",
    palavrasChave: ["Prato Cheio", "restaurante comunitário", "complementaridade"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O uso de cartão magnético no Prato Cheio tem como vantagem:",
    alternativas: [
      { texto: "facilitar o acesso ao benefício e ampliar o controle e a transparência.", correta: true },
      { texto: "impedir a compra de alimentos.", correta: false },
      { texto: "tornar a gestão menos transparente.", correta: false },
      { texto: "substituir o Cadastro Único.", correta: false },
      { texto: "elevar custos sem benefício.", correta: false },
    ],
    explicacao:
      "O cartão magnético facilita o acesso da família ao recurso e amplia o controle e a transparência sobre o uso do benefício.",
    fonteLegal: "Programa Cartão Prato Cheio (GDF/SEDES)",
    palavrasChave: ["cartão magnético", "transparência"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A revisão periódica do Cartão Prato Cheio destina-se a:",
    alternativas: [
      { texto: "verificar a permanência das condições de elegibilidade das famílias.", correta: true },
      { texto: "punir as famílias.", correta: false },
      { texto: "encerrar o programa.", correta: false },
      { texto: "beneficiar a alta renda.", correta: false },
      { texto: "eliminar o controle social.", correta: false },
    ],
    explicacao:
      "A revisão periódica garante a focalização do benefício, mantendo no programa as famílias que continuam atendendo aos critérios de elegibilidade.",
    fonteLegal: "Programa Cartão Prato Cheio; Cadastro Único",
    palavrasChave: ["revisão", "elegibilidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O Cartão Prato Cheio, como política de direito, parte da premissa de que a alimentação adequada é:",
    alternativas: [
      { texto: "um direito social previsto na Constituição Federal.", correta: true },
      { texto: "um favor concedido pelo gestor.", correta: false },
      { texto: "um privilégio das famílias de alta renda.", correta: false },
      { texto: "uma obrigação exclusiva das famílias.", correta: false },
      { texto: "um benefício contributivo.", correta: false },
    ],
    explicacao:
      "A alimentação é direito social expresso no art. 6º da CF/1988 (incluído pela EC 64/2010); o programa concretiza esse direito para as famílias vulneráveis.",
    fonteLegal: "CF/1988, art. 6º; Programa Prato Cheio",
    palavrasChave: ["direito à alimentação", "art. 6º"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A concessão do Cartão Prato Cheio depende de:",
    alternativas: [
      { texto: "atendimento aos critérios do programa e disponibilidade orçamentária do DF.", correta: true },
      { texto: "contribuição financeira das famílias.", correta: false },
      { texto: "indicação política.", correta: false },
      { texto: "doação de empresas.", correta: false },
      { texto: "filiação partidária.", correta: false },
    ],
    explicacao:
      "A concessão observa os critérios objetivos do programa e a disponibilidade orçamentária e financeira do DF, sem qualquer caráter contributivo ou político-partidário.",
    fonteLegal: "Programa Cartão Prato Cheio; LOA do DF",
    palavrasChave: ["critérios", "orçamento"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A combinação do Prato Cheio com ações de inclusão produtiva busca:",
    alternativas: [
      { texto: "promover, além do alívio imediato da fome, a autonomia e a emancipação das famílias.", correta: true },
      { texto: "manter as famílias permanentemente dependentes.", correta: false },
      { texto: "reduzir o acesso ao trabalho.", correta: false },
      { texto: "substituir a alimentação por qualificação.", correta: false },
      { texto: "eliminar a transferência de renda.", correta: false },
    ],
    explicacao:
      "A articulação com inclusão produtiva (qualificação, emprego, empreendedorismo) busca combinar o alívio imediato da insegurança alimentar com a promoção da autonomia e da emancipação das famílias.",
    fonteLegal: "Programa Prato Cheio; Plano DF Social",
    palavrasChave: ["inclusão produtiva", "autonomia"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O controle social sobre o Cartão Prato Cheio é exercido, entre outros, por:",
    alternativas: [
      { texto: "conselhos de políticas públicas e órgãos de controle, com transparência das informações.", correta: true },
      { texto: "decisões sigilosas do gestor.", correta: false },
      { texto: "empresas privadas contratadas.", correta: false },
      { texto: "ausência de qualquer controle.", correta: false },
      { texto: "organismos internacionais, exclusivamente.", correta: false },
    ],
    explicacao:
      "Como política pública, o programa sujeita-se ao controle social (conselhos) e ao controle institucional (órgãos de controle), com transparência das informações.",
    fonteLegal: "Programa Prato Cheio; LOAS; princípios da administração",
    palavrasChave: ["controle social", "transparência"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A prioridade de atendimento no Cartão Prato Cheio pode considerar:",
    alternativas: [
      { texto: "famílias em extrema pobreza e com agravantes de vulnerabilidade (ex.: crianças, idosos, PcD).", correta: true },
      { texto: "famílias de maior renda.", correta: false },
      { texto: "empresas de grande porte.", correta: false },
      { texto: "pessoas sem qualquer vulnerabilidade.", correta: false },
      { texto: "apenas servidores públicos.", correta: false },
    ],
    explicacao:
      "Os critérios de priorização costumam considerar a extrema pobreza e a presença de agravantes de vulnerabilidade (crianças, idosos, pessoas com deficiência, gestantes etc.).",
    fonteLegal: "Programa Cartão Prato Cheio (GDF/SEDES)",
    palavrasChave: ["priorização", "extrema pobreza", "agravantes"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O Prato Cheio dialoga com o princípio da intersetorialidade ao:",
    alternativas: [
      { texto: "articular segurança alimentar, assistência social e demais políticas para a proteção integral das famílias.", correta: true },
      { texto: "atuar de forma isolada das demais políticas.", correta: false },
      { texto: "substituir a política de saúde.", correta: false },
      { texto: "vedar a articulação com o SUAS.", correta: false },
      { texto: "restringir-se à área tributária.", correta: false },
    ],
    explicacao:
      "O programa articula segurança alimentar com assistência social e outras políticas, na lógica intersetorial de enfrentamento integral da pobreza e da insegurança alimentar.",
    fonteLegal: "Programa Prato Cheio; Plano DF Social",
    palavrasChave: ["intersetorialidade", "proteção integral"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O Cartão Prato Cheio é um benefício de transferência de renda do tipo:",
    alternativas: [
      { texto: "focalizado, voltado a famílias de baixa renda em insegurança alimentar.", correta: true },
      { texto: "universal, para toda a população.", correta: false },
      { texto: "contributivo.", correta: false },
      { texto: "restrito a empresas.", correta: false },
      { texto: "vinculado ao tempo de serviço.", correta: false },
    ],
    explicacao:
      "Trata-se de transferência de renda focalizada nas famílias de baixa renda em situação de insegurança alimentar, e não de benefício universal ou contributivo.",
    fonteLegal: "Programa Cartão Prato Cheio (GDF/SEDES)",
    palavrasChave: ["focalizado", "baixa renda"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Ao garantir alimentação às famílias, o Prato Cheio também contribui indiretamente para:",
    alternativas: [
      { texto: "melhores condições de saúde, frequência escolar e desenvolvimento infantil.", correta: true },
      { texto: "o aumento da evasão escolar.", correta: false },
      { texto: "a piora das condições de saúde.", correta: false },
      { texto: "a redução do desenvolvimento infantil.", correta: false },
      { texto: "o desestímulo ao acesso a direitos.", correta: false },
    ],
    explicacao:
      "A segurança alimentar tem efeitos positivos indiretos sobre saúde, aprendizagem, frequência escolar e desenvolvimento infantil, reforçando a importância do programa.",
    fonteLegal: "Programa Cartão Prato Cheio; determinantes sociais",
    palavrasChave: ["saúde", "educação", "desenvolvimento infantil"],
  },
];

export default questoes;
