import type { QSeed } from "./tipos";

const A = "Lei 840";

const questoes: QSeed[] = [
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A Lei Complementar nº 840/2011 dispõe sobre:",
    alternativas: [
      { texto: "o regime jurídico dos servidores públicos civis do Distrito Federal, das autarquias e das fundações públicas distritais.", correta: true },
      { texto: "o regime previdenciário dos trabalhadores da iniciativa privada.", correta: false },
      { texto: "a organização do sistema único de saúde do DF.", correta: false },
      { texto: "as normas de trânsito do Distrito Federal.", correta: false },
      { texto: "o estatuto das entidades filantrópicas.", correta: false },
    ],
    explicacao:
      "A LC 840/2011 institui o regime jurídico dos servidores públicos civis do DF, de suas autarquias e fundações públicas, equivalendo, no âmbito distrital, ao papel da Lei 8.112/1990 na esfera federal.",
    fonteLegal: "Lei Complementar 840/2011 (DF), art. 1º",
    palavrasChave: ["regime jurídico", "servidores", "DF"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Para investidura em cargo público regido pela Lei 840/2011, é requisito básico:",
    alternativas: [
      { texto: "a aprovação prévia em concurso público, ressalvadas as nomeações para cargo em comissão.", correta: true },
      { texto: "a indicação política, dispensado o concurso.", correta: false },
      { texto: "o pagamento de taxa de ingresso ao tesouro distrital.", correta: false },
      { texto: "ter nascido no Distrito Federal.", correta: false },
      { texto: "possuir vínculo prévio com entidade privada.", correta: false },
    ],
    explicacao:
      "A investidura em cargo público depende de aprovação prévia em concurso público de provas ou de provas e títulos, salvo as nomeações para cargo em comissão, declarado em lei de livre nomeação e exoneração.",
    fonteLegal: "Lei 840/2011; CF/1988, art. 37, II",
    palavrasChave: ["concurso público", "investidura"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "São requisitos básicos para a posse em cargo público no DF, EXCETO:",
    alternativas: [
      { texto: "nacionalidade brasileira (ou condição equiparada).", correta: false },
      { texto: "gozo dos direitos políticos.", correta: false },
      { texto: "quitação com as obrigações militares e eleitorais.", correta: false },
      { texto: "nível de escolaridade exigido para o cargo.", correta: false },
      { texto: "filiação a partido político.", correta: true },
    ],
    explicacao:
      "São requisitos básicos, entre outros, nacionalidade brasileira, gozo dos direitos políticos, quitação com obrigações militares/eleitorais, escolaridade exigida, idade mínima e aptidão. Filiação partidária não é requisito (e a imparcialidade do servidor é valor protegido).",
    fonteLegal: "Lei 840/2011 (requisitos de posse)",
    palavrasChave: ["posse", "requisitos básicos"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Conforme a Lei 840/2011, o estágio probatório do servidor nomeado para cargo efetivo tem duração de:",
    alternativas: [
      { texto: "12 meses.", correta: false },
      { texto: "24 meses.", correta: false },
      { texto: "36 meses.", correta: true },
      { texto: "48 meses.", correta: false },
      { texto: "60 meses.", correta: false },
    ],
    explicacao:
      "O estágio probatório corresponde ao período de 36 meses de efetivo exercício, durante o qual a aptidão e a capacidade do servidor são avaliadas para fins de aquisição da estabilidade.",
    fonteLegal: "Lei 840/2011, art. 22",
    palavrasChave: ["estágio probatório", "36 meses"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Durante o estágio probatório, são fatores avaliados no desempenho do servidor:",
    alternativas: [
      { texto: "assiduidade, disciplina, capacidade de iniciativa, produtividade e responsabilidade.", correta: true },
      { texto: "patrimônio pessoal e renda familiar.", correta: false },
      { texto: "orientação política e religiosa.", correta: false },
      { texto: "local de nascimento e estado civil.", correta: false },
      { texto: "número de dependentes.", correta: false },
    ],
    explicacao:
      "A avaliação do estágio probatório observa fatores como assiduidade, disciplina, capacidade de iniciativa, produtividade e responsabilidade, voltados a verificar a aptidão para o cargo.",
    fonteLegal: "Lei 840/2011, art. 22",
    palavrasChave: ["estágio probatório", "avaliação"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A estabilidade do servidor público efetivo é adquirida:",
    alternativas: [
      { texto: "após 3 anos de efetivo exercício, mediante aprovação em avaliação especial de desempenho.", correta: true },
      { texto: "no ato da posse.", correta: false },
      { texto: "após 6 meses de exercício.", correta: false },
      { texto: "automaticamente, independentemente de avaliação.", correta: false },
      { texto: "somente após 10 anos de serviço.", correta: false },
    ],
    explicacao:
      "A estabilidade é adquirida após 3 anos de efetivo exercício, sendo condição a aprovação em avaliação especial de desempenho por comissão constituída para essa finalidade.",
    fonteLegal: "Lei 840/2011; CF/1988, art. 41",
    palavrasChave: ["estabilidade", "3 anos", "avaliação"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Posse é o ato que:",
    alternativas: [
      { texto: "investe o nomeado no cargo público, com a assinatura do respectivo termo.", correta: true },
      { texto: "extingue o vínculo do servidor com a Administração.", correta: false },
      { texto: "transfere o servidor para outro órgão.", correta: false },
      { texto: "concede aposentadoria ao servidor.", correta: false },
      { texto: "aplica penalidade disciplinar.", correta: false },
    ],
    explicacao:
      "A posse é o ato de investidura no cargo público, com a aceitação expressa das atribuições, deveres e responsabilidades, formalizada pela assinatura do termo de posse.",
    fonteLegal: "Lei 840/2011 (provimento e posse)",
    palavrasChave: ["posse", "investidura"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Exercício é:",
    alternativas: [
      { texto: "o efetivo desempenho das atribuições do cargo pelo servidor.", correta: true },
      { texto: "o ato de nomeação publicado no Diário Oficial.", correta: false },
      { texto: "o período de afastamento para tratamento de saúde.", correta: false },
      { texto: "a vacância do cargo por aposentadoria.", correta: false },
      { texto: "a remoção a pedido.", correta: false },
    ],
    explicacao:
      "Exercício é o efetivo desempenho das atribuições do cargo. É a partir do início do exercício que se contam, por exemplo, prazos relativos ao estágio probatório.",
    fonteLegal: "Lei 840/2011 (exercício)",
    palavrasChave: ["exercício", "atribuições"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "São formas de provimento de cargo público previstas na Lei 840/2011:",
    alternativas: [
      { texto: "nomeação, promoção, readaptação, reversão, reintegração, recondução e aproveitamento.", correta: true },
      { texto: "exoneração, demissão e cassação de aposentadoria.", correta: false },
      { texto: "licença, férias e afastamento.", correta: false },
      { texto: "advertência, suspensão e multa.", correta: false },
      { texto: "remoção, redistribuição e substituição.", correta: false },
    ],
    explicacao:
      "As formas de provimento incluem nomeação, promoção, readaptação, reversão, reintegração, recondução e aproveitamento. Exoneração e demissão são formas de vacância (desligamento), não de provimento.",
    fonteLegal: "Lei 840/2011 (formas de provimento)",
    palavrasChave: ["provimento", "nomeação", "reintegração"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A reintegração, como forma de provimento, ocorre quando:",
    alternativas: [
      { texto: "o servidor estável retorna ao cargo após invalidação de sua demissão, com ressarcimento de vantagens.", correta: true },
      { texto: "o servidor é nomeado pela primeira vez.", correta: false },
      { texto: "o aposentado retorna ao trabalho por interesse próprio sem requisitos.", correta: false },
      { texto: "o servidor é promovido por antiguidade.", correta: false },
      { texto: "o servidor é removido a pedido.", correta: false },
    ],
    explicacao:
      "A reintegração é o retorno do servidor estável ao cargo de origem, em razão da invalidação (administrativa ou judicial) de sua demissão, com ressarcimento das vantagens do período de afastamento.",
    fonteLegal: "Lei 840/2011 (reintegração); CF/1988, art. 41, §2º",
    palavrasChave: ["reintegração", "demissão invalidada"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "São formas de vacância de cargo público:",
    alternativas: [
      { texto: "exoneração, demissão, aposentadoria, posse em outro cargo inacumulável e falecimento.", correta: true },
      { texto: "nomeação e promoção.", correta: false },
      { texto: "advertência e suspensão.", correta: false },
      { texto: "férias e licença-prêmio.", correta: false },
      { texto: "reversão e reintegração.", correta: false },
    ],
    explicacao:
      "A vacância decorre, entre outras hipóteses, de exoneração, demissão, promoção, aposentadoria, posse em outro cargo inacumulável e falecimento.",
    fonteLegal: "Lei 840/2011 (vacância)",
    palavrasChave: ["vacância", "exoneração", "demissão"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A diferença essencial entre exoneração e demissão é que:",
    alternativas: [
      { texto: "a demissão tem caráter de penalidade disciplinar; a exoneração, não.", correta: true },
      { texto: "ambas são sempre penalidades.", correta: false },
      { texto: "a exoneração só ocorre por decisão judicial.", correta: false },
      { texto: "a demissão é ato de provimento.", correta: false },
      { texto: "não há qualquer diferença entre elas.", correta: false },
    ],
    explicacao:
      "A demissão é penalidade disciplinar aplicada após processo administrativo. A exoneração não tem natureza punitiva (pode ser a pedido ou de ofício, por exemplo, de cargo em comissão).",
    fonteLegal: "Lei 840/2011",
    palavrasChave: ["exoneração", "demissão", "penalidade"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "São deveres do servidor público, segundo a Lei 840/2011:",
    alternativas: [
      { texto: "exercer com zelo e dedicação as atribuições e ser leal às instituições.", correta: true },
      { texto: "valer-se do cargo para obter proveito pessoal.", correta: false },
      { texto: "recusar fé a documentos públicos.", correta: false },
      { texto: "participar da gerência de empresa privada como sócio-gerente.", correta: false },
      { texto: "ausentar-se do serviço sem autorização.", correta: false },
    ],
    explicacao:
      "Entre os deveres estão exercer com zelo e dedicação as atribuições, ser leal às instituições, observar normas legais e regulamentares e cumprir as ordens superiores, salvo quando manifestamente ilegais.",
    fonteLegal: "Lei 840/2011 (deveres)",
    palavrasChave: ["deveres", "zelo", "lealdade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Constitui proibição ao servidor público:",
    alternativas: [
      { texto: "valer-se do cargo para lograr proveito pessoal ou de outrem, em detrimento da dignidade da função.", correta: true },
      { texto: "cumprir as ordens legais de seus superiores.", correta: false },
      { texto: "tratar com urbanidade as pessoas.", correta: false },
      { texto: "guardar sigilo sobre assuntos da repartição.", correta: false },
      { texto: "zelar pela economia do material público.", correta: false },
    ],
    explicacao:
      "É vedado ao servidor valer-se do cargo para obter proveito pessoal ou de outrem; as demais alternativas descrevem deveres, não proibições.",
    fonteLegal: "Lei 840/2011 (proibições)",
    palavrasChave: ["proibições", "proveito pessoal"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "As penalidades disciplinares previstas na Lei 840/2011 incluem:",
    alternativas: [
      { texto: "advertência, suspensão, demissão, cassação de aposentadoria/disponibilidade e destituição de cargo em comissão.", correta: true },
      { texto: "prisão e multa criminal.", correta: false },
      { texto: "remoção e redistribuição.", correta: false },
      { texto: "promoção e progressão.", correta: false },
      { texto: "férias e licenças.", correta: false },
    ],
    explicacao:
      "As penalidades disciplinares são advertência, suspensão, demissão, cassação de aposentadoria ou disponibilidade e destituição de cargo em comissão ou de função, conforme a gravidade da infração.",
    fonteLegal: "Lei 840/2011 (penalidades)",
    palavrasChave: ["penalidades", "advertência", "demissão"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A penalidade de advertência aplica-se, em regra, a infrações:",
    alternativas: [
      { texto: "de menor gravidade, sendo a sanção mais branda do regime disciplinar.", correta: true },
      { texto: "que exigem necessariamente a demissão.", correta: false },
      { texto: "de natureza criminal.", correta: false },
      { texto: "praticadas apenas por servidores em estágio probatório.", correta: false },
      { texto: "que resultam em cassação de aposentadoria.", correta: false },
    ],
    explicacao:
      "A advertência é a penalidade mais branda, aplicada a infrações leves (como violação de deveres ou proibições de menor gravidade), normalmente registrada por escrito.",
    fonteLegal: "Lei 840/2011",
    palavrasChave: ["advertência", "infração leve"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A apuração de irregularidade funcional grave, que possa resultar em demissão, deve observar:",
    alternativas: [
      { texto: "o devido processo legal, com contraditório e ampla defesa, em processo administrativo disciplinar (PAD).", correta: true },
      { texto: "decisão sumária do chefe imediato, sem defesa.", correta: false },
      { texto: "apenas a comunicação verbal ao servidor.", correta: false },
      { texto: "exclusivamente a via judicial penal.", correta: false },
      { texto: "voto de conselho de assistência social.", correta: false },
    ],
    explicacao:
      "Penalidades graves (suspensão prolongada, demissão, cassação) exigem processo administrativo disciplinar, assegurados o contraditório e a ampla defesa, sob pena de nulidade.",
    fonteLegal: "Lei 840/2011 (PAD); CF/1988, art. 5º, LV",
    palavrasChave: ["PAD", "ampla defesa", "contraditório"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Sobre acumulação de cargos públicos, a regra constitucional aplicável ao servidor do DF é:",
    alternativas: [
      { texto: "a vedação à acumulação remunerada, salvo as exceções constitucionais (ex.: dois cargos de professor; cargo de professor com técnico/científico; dois na área de saúde com profissões regulamentadas), havendo compatibilidade de horários.", correta: true },
      { texto: "a livre acumulação de quaisquer cargos.", correta: false },
      { texto: "a proibição absoluta de qualquer acumulação, sem exceções.", correta: false },
      { texto: "a acumulação condicionada apenas à autorização do chefe.", correta: false },
      { texto: "a permissão de acumular três cargos de saúde.", correta: false },
    ],
    explicacao:
      "Em regra, é vedada a acumulação remunerada de cargos públicos, com exceções constitucionais taxativas (dois de professor; um de professor com outro técnico/científico; dois privativos de saúde), sempre exigida a compatibilidade de horários.",
    fonteLegal: "CF/1988, art. 37, XVI; Lei 840/2011",
    palavrasChave: ["acumulação", "exceções", "compatibilidade de horários"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Vencimento, na Lei 840/2011, corresponde a:",
    alternativas: [
      { texto: "a retribuição pecuniária pelo exercício de cargo público, com valor fixado em lei.", correta: true },
      { texto: "ao conjunto de todas as vantagens somadas ao subsídio.", correta: false },
      { texto: "a um benefício previdenciário.", correta: false },
      { texto: "a uma penalidade pecuniária.", correta: false },
      { texto: "a uma gratificação eventual.", correta: false },
    ],
    explicacao:
      "Vencimento é a retribuição pecuniária pelo efetivo exercício do cargo, com valor fixado em lei. A remuneração é o vencimento acrescido das vantagens pecuniárias permanentes ou temporárias.",
    fonteLegal: "Lei 840/2011 (vencimento e remuneração)",
    palavrasChave: ["vencimento", "remuneração"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "São exemplos de licenças que podem ser concedidas ao servidor do DF:",
    alternativas: [
      { texto: "licença para tratamento da própria saúde, licença à gestante e licença por motivo de doença em pessoa da família.", correta: true },
      { texto: "licença para exercício de cargo eletivo em empresa privada.", correta: false },
      { texto: "licença para acumular cargos inacumuláveis.", correta: false },
      { texto: "licença para descumprir ordens legais.", correta: false },
      { texto: "licença para uso do cargo em proveito pessoal.", correta: false },
    ],
    explicacao:
      "Entre as licenças previstas estão a licença para tratamento de saúde, a licença à gestante/adotante, a licença-paternidade e a licença por motivo de doença em pessoa da família, conforme requisitos legais.",
    fonteLegal: "Lei 840/2011 (licenças)",
    palavrasChave: ["licenças", "saúde", "gestante"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A readaptação, prevista na Lei 840/2011, consiste em:",
    alternativas: [
      { texto: "investir o servidor em cargo de atribuições compatíveis com limitação física/mental sofrida, verificada em inspeção médica.", correta: true },
      { texto: "demitir o servidor por incapacidade.", correta: false },
      { texto: "promover o servidor por merecimento.", correta: false },
      { texto: "remover o servidor a pedido para outra cidade.", correta: false },
      { texto: "aposentar compulsoriamente o servidor.", correta: false },
    ],
    explicacao:
      "A readaptação é a investidura do servidor em cargo de atribuições e responsabilidades compatíveis com a limitação que tenha sofrido em sua capacidade física ou mental, apurada em inspeção médica.",
    fonteLegal: "Lei 840/2011 (readaptação)",
    palavrasChave: ["readaptação", "limitação", "inspeção médica"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A recondução, como forma de provimento, ocorre quando:",
    alternativas: [
      { texto: "o servidor estável retorna ao cargo anterior por inabilitação em estágio probatório de outro cargo ou por reintegração do antigo ocupante.", correta: true },
      { texto: "o servidor é aproveitado após disponibilidade.", correta: false },
      { texto: "o servidor é nomeado para cargo em comissão.", correta: false },
      { texto: "o servidor é promovido por antiguidade.", correta: false },
      { texto: "o servidor é exonerado a pedido.", correta: false },
    ],
    explicacao:
      "A recondução é o retorno do servidor estável ao cargo anteriormente ocupado, decorrente de inabilitação em estágio probatório relativo a outro cargo ou de reintegração do anterior ocupante.",
    fonteLegal: "Lei 840/2011 (recondução)",
    palavrasChave: ["recondução", "estágio probatório", "estável"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Cargo em comissão caracteriza-se por ser:",
    alternativas: [
      { texto: "de livre nomeação e exoneração, destinado às atribuições de direção, chefia e assessoramento.", correta: true },
      { texto: "de provimento exclusivamente por concurso público.", correta: false },
      { texto: "vitalício após a posse.", correta: false },
      { texto: "vedado a servidores efetivos.", correta: false },
      { texto: "estável a partir de três anos.", correta: false },
    ],
    explicacao:
      "O cargo em comissão é de livre nomeação e exoneração, destinado apenas às atribuições de direção, chefia e assessoramento, conforme a Constituição e a Lei 840/2011.",
    fonteLegal: "Lei 840/2011; CF/1988, art. 37, V",
    palavrasChave: ["cargo em comissão", "livre nomeação"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O prazo prescricional e a independência das instâncias significam, no regime disciplinar, que:",
    alternativas: [
      { texto: "as responsabilidades civil, penal e administrativa são independentes e podem cumular-se.", correta: true },
      { texto: "a punição administrativa exclui sempre a penal.", correta: false },
      { texto: "a absolvição administrativa impede qualquer ação civil.", correta: false },
      { texto: "só pode haver uma única responsabilização.", correta: false },
      { texto: "a esfera penal depende sempre da administrativa.", correta: false },
    ],
    explicacao:
      "As instâncias civil, penal e administrativa são, em regra, independentes, podendo o servidor responder cumulativamente. A absolvição penal só repercute na esfera administrativa quando negar a existência do fato ou a autoria.",
    fonteLegal: "Lei 840/2011 (responsabilidades)",
    palavrasChave: ["independência das instâncias", "responsabilidade"],
  },
];

export default questoes;
