import type { QSeed } from "./tipos";

const A = "Lei Maria da Penha";

const questoes: QSeed[] = [
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A Lei Maria da Penha (Lei 11.340/2006) tem por finalidade:",
    alternativas: [
      { texto: "criar mecanismos para coibir e prevenir a violência doméstica e familiar contra a mulher.", correta: true },
      { texto: "regular o regime previdenciário das mulheres.", correta: false },
      { texto: "tratar exclusivamente de crimes de trânsito.", correta: false },
      { texto: "organizar a política nacional de saúde da mulher.", correta: false },
      { texto: "disciplinar a guarda compartilhada de filhos.", correta: false },
    ],
    explicacao:
      "A Lei 11.340/2006 cria mecanismos para coibir e prevenir a violência doméstica e familiar contra a mulher, nos termos do art. 226, §8º, da CF e de tratados internacionais ratificados pelo Brasil.",
    fonteLegal: "Lei 11.340/2006, art. 1º",
    palavrasChave: ["finalidade", "violência doméstica"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Constituem formas de violência doméstica e familiar contra a mulher, segundo o art. 7º da Lei 11.340/2006:",
    alternativas: [
      { texto: "violência física, psicológica, sexual, patrimonial e moral.", correta: true },
      { texto: "violência física, ambiental, digital e tributária.", correta: false },
      { texto: "apenas violência física e sexual.", correta: false },
      { texto: "violência cultural, esportiva e religiosa.", correta: false },
      { texto: "somente violência patrimonial.", correta: false },
    ],
    explicacao:
      "O art. 7º enumera cinco formas: física, psicológica, sexual, patrimonial e moral. O rol é exemplificativo ('entre outras').",
    fonteLegal: "Lei 11.340/2006, art. 7º",
    palavrasChave: ["formas de violência", "art. 7º"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A violência patrimonial, na Lei Maria da Penha, caracteriza-se por:",
    alternativas: [
      { texto: "reter, subtrair, destruir parcial ou totalmente objetos, instrumentos de trabalho, documentos e bens da mulher.", correta: true },
      { texto: "causar dano emocional e diminuição da autoestima.", correta: false },
      { texto: "constranger a presenciar relação sexual.", correta: false },
      { texto: "ofender a honra ou reputação.", correta: false },
      { texto: "causar lesão à integridade corporal.", correta: false },
    ],
    explicacao:
      "A violência patrimonial é entendida como qualquer conduta que configure retenção, subtração, destruição de bens, valores, documentos, instrumentos de trabalho e direitos da mulher.",
    fonteLegal: "Lei 11.340/2006, art. 7º, IV",
    palavrasChave: ["violência patrimonial", "bens"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A violência moral, conforme a Lei 11.340/2006, é entendida como conduta que configure:",
    alternativas: [
      { texto: "calúnia, difamação ou injúria.", correta: true },
      { texto: "lesão corporal.", correta: false },
      { texto: "estupro.", correta: false },
      { texto: "destruição de bens.", correta: false },
      { texto: "humilhação por chantagem.", correta: false },
    ],
    explicacao:
      "A violência moral é entendida como qualquer conduta que configure calúnia, difamação ou injúria (crimes contra a honra).",
    fonteLegal: "Lei 11.340/2006, art. 7º, V",
    palavrasChave: ["violência moral", "honra"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A configuração da violência doméstica e familiar contra a mulher independe de:",
    alternativas: [
      { texto: "orientação sexual da mulher, aplicando-se a lei independentemente dessa condição.", correta: true },
      { texto: "existência de relação doméstica, familiar ou de afeto.", correta: false },
      { texto: "ação ou omissão baseada no gênero.", correta: false },
      { texto: "ocorrência de dano à mulher.", correta: false },
      { texto: "âmbito de unidade doméstica, família ou relação íntima.", correta: false },
    ],
    explicacao:
      "O parágrafo único do art. 5º estabelece que as relações pessoais ali enunciadas independem de orientação sexual. A lei protege a mulher em razão do gênero, no contexto doméstico, familiar ou de relação íntima de afeto.",
    fonteLegal: "Lei 11.340/2006, art. 5º, parágrafo único",
    palavrasChave: ["orientação sexual", "gênero"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Os âmbitos em que se configura a violência doméstica e familiar, segundo o art. 5º, incluem:",
    alternativas: [
      { texto: "a unidade doméstica, a família e qualquer relação íntima de afeto, independentemente de coabitação.", correta: true },
      { texto: "apenas o casamento civil.", correta: false },
      { texto: "somente quando há coabitação atual.", correta: false },
      { texto: "exclusivamente relações com vínculo de parentesco consanguíneo.", correta: false },
      { texto: "apenas o ambiente de trabalho.", correta: false },
    ],
    explicacao:
      "Configura-se no âmbito da unidade doméstica, da família e em qualquer relação íntima de afeto, na qual o agressor conviva ou tenha convivido com a ofendida, independentemente de coabitação.",
    fonteLegal: "Lei 11.340/2006, art. 5º",
    palavrasChave: ["âmbitos", "relação íntima", "coabitação"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Segundo a Lei 11.340/2006, a violência doméstica e familiar contra a mulher constitui:",
    alternativas: [
      { texto: "uma das formas de violação dos direitos humanos.", correta: true },
      { texto: "mera questão de foro privado, sem relevância pública.", correta: false },
      { texto: "infração de menor potencial ofensivo em todos os casos.", correta: false },
      { texto: "conduta atípica.", correta: false },
      { texto: "matéria exclusivamente cível.", correta: false },
    ],
    explicacao:
      "O art. 6º declara que a violência doméstica e familiar contra a mulher constitui uma das formas de violação dos direitos humanos.",
    fonteLegal: "Lei 11.340/2006, art. 6º",
    palavrasChave: ["direitos humanos", "violência"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "As medidas protetivas de urgência que obrigam o agressor incluem:",
    alternativas: [
      { texto: "afastamento do lar e proibição de aproximação da ofendida, fixando limite mínimo de distância.", correta: true },
      { texto: "encaminhamento da ofendida a programa de proteção.", correta: false },
      { texto: "recondução da ofendida ao lar após o afastamento do agressor.", correta: false },
      { texto: "separação de corpos a pedido da vítima.", correta: false },
      { texto: "restituição de bens à ofendida.", correta: false },
    ],
    explicacao:
      "Entre as medidas que obrigam o agressor (art. 22) estão o afastamento do lar e a proibição de aproximação/contato com a ofendida, com fixação de distância mínima. As demais alternativas são medidas dirigidas à ofendida (arts. 23 e 24).",
    fonteLegal: "Lei 11.340/2006, art. 22",
    palavrasChave: ["medidas protetivas", "agressor"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "São medidas protetivas de urgência à ofendida, previstas na Lei Maria da Penha:",
    alternativas: [
      { texto: "encaminhamento a programa de proteção e recondução ao domicílio após afastamento do agressor.", correta: true },
      { texto: "prisão preventiva do agressor.", correta: false },
      { texto: "suspensão da posse de armas do agressor.", correta: false },
      { texto: "afastamento do agressor do lar.", correta: false },
      { texto: "prestação de alimentos pelo agressor.", correta: false },
    ],
    explicacao:
      "As medidas dirigidas à ofendida (arts. 23 e 24) incluem encaminhá-la, com seus dependentes, a programa de proteção/atendimento e reconduzi-la ao domicílio após o afastamento do agressor, além da proteção de seus bens.",
    fonteLegal: "Lei 11.340/2006, arts. 23 e 24",
    palavrasChave: ["medidas protetivas", "ofendida"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "Sobre o juizado competente, a Lei 11.340/2006 prevê:",
    alternativas: [
      { texto: "os Juizados de Violência Doméstica e Familiar contra a Mulher, com competência cível e criminal.", correta: true },
      { texto: "competência exclusiva dos juizados especiais criminais.", correta: false },
      { texto: "competência apenas da justiça do trabalho.", correta: false },
      { texto: "competência apenas cível, sem matéria criminal.", correta: false },
      { texto: "competência da justiça eleitoral.", correta: false },
    ],
    explicacao:
      "A lei prevê a criação dos Juizados de Violência Doméstica e Familiar contra a Mulher (JVDFM), com competência cível e criminal para as causas decorrentes da violência doméstica.",
    fonteLegal: "Lei 11.340/2006, art. 14",
    palavrasChave: ["juizado", "competência cível e criminal"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Quanto à aplicação da Lei 9.099/95 (Juizados Especiais) aos crimes da Lei Maria da Penha:",
    alternativas: [
      { texto: "é vedada a aplicação da Lei 9.099/95 aos crimes praticados com violência doméstica e familiar contra a mulher.", correta: true },
      { texto: "aplica-se integralmente a Lei 9.099/95.", correta: false },
      { texto: "permite-se transação penal em qualquer caso.", correta: false },
      { texto: "permite-se a pena de cesta básica.", correta: false },
      { texto: "aplica-se apenas a suspensão condicional do processo.", correta: false },
    ],
    explicacao:
      "O art. 41 veda expressamente a aplicação da Lei 9.099/95 aos crimes praticados com violência doméstica e familiar contra a mulher, afastando institutos como a transação penal nesses casos.",
    fonteLegal: "Lei 11.340/2006, art. 41",
    palavrasChave: ["Lei 9.099/95", "vedação", "art. 41"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "Conforme entendimento consolidado (Súmula 542 do STJ) e a jurisprudência, a ação penal nos crimes de lesão corporal praticados contra a mulher no âmbito doméstico é:",
    alternativas: [
      { texto: "pública incondicionada.", correta: true },
      { texto: "pública condicionada à representação.", correta: false },
      { texto: "privada.", correta: false },
      { texto: "personalíssima.", correta: false },
      { texto: "subsidiária da pública.", correta: false },
    ],
    explicacao:
      "Segundo a Súmula 542 do STJ, a ação penal relativa ao crime de lesão corporal resultante de violência doméstica contra a mulher é pública incondicionada, dispensando representação da vítima.",
    fonteLegal: "Súmula 542 STJ; Lei 11.340/2006",
    palavrasChave: ["ação penal", "incondicionada", "lesão corporal"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A renúncia/retratação da representação pela ofendida, nos casos em que cabível, somente é admitida:",
    alternativas: [
      { texto: "perante o juiz, em audiência especialmente designada antes do recebimento da denúncia, ouvido o Ministério Público.", correta: true },
      { texto: "verbalmente, na delegacia, sem qualquer formalidade.", correta: false },
      { texto: "a qualquer tempo, inclusive após o trânsito em julgado.", correta: false },
      { texto: "por escrito, sem participação do juiz.", correta: false },
      { texto: "somente após a condenação.", correta: false },
    ],
    explicacao:
      "Nos crimes de ação penal pública condicionada, a retratação da representação só é admitida perante o juiz, em audiência especialmente designada para tal fim, antes do recebimento da denúncia e ouvido o MP (art. 16).",
    fonteLegal: "Lei 11.340/2006, art. 16",
    palavrasChave: ["retratação", "representação", "audiência"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A assistência à mulher em situação de violência doméstica será prestada de forma:",
    alternativas: [
      { texto: "articulada e conforme princípios e diretrizes de diversas políticas, incluindo assistência social, saúde e segurança pública.", correta: true },
      { texto: "exclusivamente pela área da segurança pública.", correta: false },
      { texto: "apenas mediante pagamento pela vítima.", correta: false },
      { texto: "somente por entidades privadas.", correta: false },
      { texto: "isoladamente pela área da saúde.", correta: false },
    ],
    explicacao:
      "A assistência à mulher será prestada de forma articulada, conforme os princípios e diretrizes do SUS, do SUAS e de outras normas e políticas públicas de proteção (art. 9º), com atuação intersetorial.",
    fonteLegal: "Lei 11.340/2006, art. 9º",
    palavrasChave: ["assistência", "intersetorial", "SUAS"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A inclusão da mulher em situação de violência doméstica no Cadastro Único e em programas assistenciais relaciona-se a:",
    alternativas: [
      { texto: "medidas de assistência social que integram a proteção prevista na lei.", correta: true },
      { texto: "uma penalidade imposta à vítima.", correta: false },
      { texto: "um requisito para registrar a ocorrência.", correta: false },
      { texto: "uma condição para a prisão do agressor.", correta: false },
      { texto: "uma vedação legal.", correta: false },
    ],
    explicacao:
      "A lei prevê que a ofendida seja incluída em cadastro de programas assistenciais do governo, conectando a proteção da mulher à rede de assistência social (art. 9º, §1º).",
    fonteLegal: "Lei 11.340/2006, art. 9º, §1º",
    palavrasChave: ["Cadastro Único", "assistência social"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Quanto ao atendimento pela autoridade policial, a Lei Maria da Penha determina que, havendo risco à vida ou à integridade da mulher, a autoridade:",
    alternativas: [
      { texto: "poderá, em casos previstos, aplicar medida protetiva de urgência de afastamento do agressor do lar.", correta: true },
      { texto: "deverá arquivar a ocorrência.", correta: false },
      { texto: "encaminhará a vítima para fora do país.", correta: false },
      { texto: "ficará impedida de tomar qualquer providência.", correta: false },
      { texto: "exigirá o pagamento de fiança pela vítima.", correta: false },
    ],
    explicacao:
      "A Lei 13.827/2019 incluiu a possibilidade de aplicação de medida protetiva de afastamento do agressor pela autoridade policial (ou pelo delegado), em municípios sem juiz/comarca, quando houver risco atual ou iminente à vida ou integridade da mulher.",
    fonteLegal: "Lei 11.340/2006, art. 12-C (incluído pela Lei 13.827/2019)",
    palavrasChave: ["medida protetiva", "autoridade policial", "risco"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O registro da ocorrência de violência doméstica e o pedido de medidas protetivas:",
    alternativas: [
      { texto: "independem do pagamento de custas ou despesas pela ofendida.", correta: true },
      { texto: "exigem advogado em todas as fases para o registro.", correta: false },
      { texto: "dependem de autorização do agressor.", correta: false },
      { texto: "só podem ser feitos pela própria vítima, sem auxílio.", correta: false },
      { texto: "exigem prévia condenação criminal.", correta: false },
    ],
    explicacao:
      "A proteção à mulher é prestada de forma gratuita. A ofendida pode requerer medidas protetivas independentemente de custas, sendo-lhe garantido acesso aos serviços de defensoria e assistência judiciária.",
    fonteLegal: "Lei 11.340/2006 (acesso e gratuidade)",
    palavrasChave: ["gratuidade", "medidas protetivas"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A violência psicológica, na Lei 11.340/2006, abrange condutas que causem:",
    alternativas: [
      { texto: "dano emocional, diminuição da autoestima ou que prejudiquem o pleno desenvolvimento da mulher.", correta: true },
      { texto: "apenas lesões corporais visíveis.", correta: false },
      { texto: "somente prejuízos financeiros.", correta: false },
      { texto: "exclusivamente ofensas à honra.", correta: false },
      { texto: "apenas constrangimento a ato sexual.", correta: false },
    ],
    explicacao:
      "A violência psicológica é entendida como conduta que cause dano emocional e diminuição da autoestima, prejudique e perturbe o pleno desenvolvimento da mulher ou vise degradar/controlar suas ações e crenças.",
    fonteLegal: "Lei 11.340/2006, art. 7º, II",
    palavrasChave: ["violência psicológica", "dano emocional"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A Lei 11.340/2006 fundamenta-se constitucionalmente, sobretudo, no dispositivo que prevê:",
    alternativas: [
      { texto: "o dever do Estado de coibir a violência no âmbito das relações familiares (art. 226, §8º, da CF).", correta: true },
      { texto: "a função social da propriedade.", correta: false },
      { texto: "a livre concorrência.", correta: false },
      { texto: "a autonomia universitária.", correta: false },
      { texto: "a anterioridade tributária.", correta: false },
    ],
    explicacao:
      "A lei se fundamenta no art. 226, §8º, da CF/1988, que impõe ao Estado o dever de criar mecanismos para coibir a violência no âmbito das relações familiares, além de convenções internacionais (Belém do Pará e CEDAW).",
    fonteLegal: "CF/1988, art. 226, §8º; Lei 11.340/2006, art. 1º",
    palavrasChave: ["fundamento constitucional", "art. 226"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A violência sexual, conforme a Lei Maria da Penha, inclui:",
    alternativas: [
      { texto: "constranger a mulher a presenciar, manter ou participar de relação sexual não desejada, mediante intimidação, ameaça ou coação.", correta: true },
      { texto: "apenas a subtração de bens.", correta: false },
      { texto: "somente calúnia e difamação.", correta: false },
      { texto: "exclusivamente dano à autoestima.", correta: false },
      { texto: "apenas lesão corporal.", correta: false },
    ],
    explicacao:
      "A violência sexual é qualquer conduta que constranja a mulher a presenciar, manter ou participar de relação sexual não desejada, ou que limite/anule o exercício de seus direitos sexuais e reprodutivos.",
    fonteLegal: "Lei 11.340/2006, art. 7º, III",
    palavrasChave: ["violência sexual", "direitos reprodutivos"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Para os efeitos da Lei Maria da Penha, considera-se que a proteção destina-se:",
    alternativas: [
      { texto: "à mulher em situação de violência doméstica e familiar, em razão do gênero.", correta: true },
      { texto: "a qualquer pessoa, sem distinção de contexto.", correta: false },
      { texto: "apenas a mulheres casadas.", correta: false },
      { texto: "somente a mulheres com filhos.", correta: false },
      { texto: "exclusivamente a idosas.", correta: false },
    ],
    explicacao:
      "A lei protege a mulher contra a violência doméstica e familiar baseada no gênero, no contexto da unidade doméstica, da família ou de relação íntima de afeto.",
    fonteLegal: "Lei 11.340/2006, arts. 2º e 5º",
    palavrasChave: ["gênero", "mulher", "proteção"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O descumprimento de medida protetiva de urgência deferida pelo juiz:",
    alternativas: [
      { texto: "configura crime previsto na própria Lei Maria da Penha.", correta: true },
      { texto: "é conduta atípica.", correta: false },
      { texto: "gera apenas multa administrativa.", correta: false },
      { texto: "é mera irregularidade cível.", correta: false },
      { texto: "depende de nova representação da vítima para qualquer providência.", correta: false },
    ],
    explicacao:
      "A Lei 13.641/2018 incluiu o art. 24-A na Lei 11.340/2006, tipificando como crime o descumprimento de medidas protetivas de urgência deferidas pelo juiz.",
    fonteLegal: "Lei 11.340/2006, art. 24-A (Lei 13.641/2018)",
    palavrasChave: ["descumprimento", "medida protetiva", "crime"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "As medidas protetivas de urgência podem ser concedidas pelo juiz:",
    alternativas: [
      { texto: "a requerimento do Ministério Público ou a pedido da ofendida, podendo ser aplicadas de imediato.", correta: true },
      { texto: "somente após a conclusão do processo penal.", correta: false },
      { texto: "apenas mediante perícia prévia obrigatória.", correta: false },
      { texto: "exclusivamente por iniciativa do agressor.", correta: false },
      { texto: "somente em segunda instância.", correta: false },
    ],
    explicacao:
      "As medidas protetivas podem ser concedidas pelo juiz, a requerimento do MP ou a pedido da ofendida, de imediato e independentemente de audiência das partes, podendo ser substituídas ou ampliadas a qualquer tempo.",
    fonteLegal: "Lei 11.340/2006, arts. 18 e 19",
    palavrasChave: ["medidas protetivas", "concessão", "imediata"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A criação de centros de atendimento integral, casas-abrigo e delegacias especializadas, prevista na lei, integra:",
    alternativas: [
      { texto: "as medidas de assistência e prevenção à violência doméstica e familiar contra a mulher.", correta: true },
      { texto: "as penalidades aplicáveis à vítima.", correta: false },
      { texto: "as regras de acumulação de cargos.", correta: false },
      { texto: "as normas tributárias do DF.", correta: false },
      { texto: "as hipóteses de arquivamento da ocorrência.", correta: false },
    ],
    explicacao:
      "A lei prevê a criação de equipamentos como centros de atendimento integral e multidisciplinar, casas-abrigo, delegacias e núcleos especializados, no âmbito das medidas integradas de prevenção e assistência.",
    fonteLegal: "Lei 11.340/2006, arts. 8º e 35",
    palavrasChave: ["casa-abrigo", "delegacia especializada", "prevenção"],
  },
];

export default questoes;
