import type { QSeed } from "./tipos";

const A = "NOB SUAS";

const questoes: QSeed[] = [
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A NOB-SUAS tem como objeto principal:",
    alternativas: [
      { texto: "disciplinar a gestão pública da política de assistência social no território nacional.", correta: true },
      { texto: "regular o sistema de saúde suplementar.", correta: false },
      { texto: "criar o regime previdenciário dos servidores.", correta: false },
      { texto: "definir o orçamento da educação básica.", correta: false },
      { texto: "organizar o sistema tributário nacional.", correta: false },
    ],
    explicacao:
      "A Norma Operacional Básica do SUAS (NOB-SUAS) disciplina a gestão pública da política de assistência social, exercida de modo sistêmico pelos entes federativos.",
    fonteLegal: "NOB-SUAS/2012 (Resolução CNAS nº 33/2012)",
    palavrasChave: ["NOB", "gestão", "SUAS"],
  },
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Os níveis de gestão dos municípios no SUAS, conforme a NOB, são:",
    alternativas: [
      { texto: "inicial, básica e plena.", correta: true },
      { texto: "simples, intermediária e avançada.", correta: false },
      { texto: "mínima, média e máxima.", correta: false },
      { texto: "provisória, definitiva e especial.", correta: false },
      { texto: "única e exclusiva.", correta: false },
    ],
    explicacao:
      "A NOB-SUAS estabeleceu níveis de gestão para os municípios — inicial, básica e plena — conforme o cumprimento de requisitos de organização e oferta da política.",
    fonteLegal: "NOB-SUAS",
    palavrasChave: ["níveis de gestão", "inicial", "plena"],
  },
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "As instâncias de pactuação intergovernamental do SUAS são:",
    alternativas: [
      { texto: "a CIT (Comissão Intergestores Tripartite) e as CIBs (Comissões Intergestores Bipartites).", correta: true },
      { texto: "o Congresso Nacional e as Assembleias Legislativas.", correta: false },
      { texto: "os tribunais de contas da União e dos estados.", correta: false },
      { texto: "as agências reguladoras federais.", correta: false },
      { texto: "os conselhos tutelares municipais.", correta: false },
    ],
    explicacao:
      "A pactuação no SUAS ocorre na Comissão Intergestores Tripartite (CIT), com União, estados e municípios, e nas Comissões Intergestores Bipartites (CIB), com estado e municípios.",
    fonteLegal: "NOB-SUAS",
    palavrasChave: ["CIT", "CIB", "pactuação"],
  },
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "As instâncias de deliberação do SUAS, de caráter permanente e paritário, são:",
    alternativas: [
      { texto: "os conselhos de assistência social.", correta: true },
      { texto: "as comissões intergestores.", correta: false },
      { texto: "os fundos de assistência social.", correta: false },
      { texto: "as secretarias executivas.", correta: false },
      { texto: "as entidades privadas.", correta: false },
    ],
    explicacao:
      "Enquanto a pactuação ocorre nas comissões intergestores, a deliberação e o controle social cabem aos conselhos de assistência social, paritários e permanentes.",
    fonteLegal: "NOB-SUAS; LOAS",
    palavrasChave: ["conselhos", "deliberação", "controle social"],
  },
  {
    assunto: A,
    subassunto: "Financiamento",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O cofinanciamento federal do SUAS, em regra, é repassado:",
    alternativas: [
      { texto: "de forma regular e automática, fundo a fundo, por meio de blocos de financiamento.", correta: true },
      { texto: "por convênios pontuais e isolados para cada serviço.", correta: false },
      { texto: "diretamente às famílias beneficiárias em espécie.", correta: false },
      { texto: "exclusivamente por emendas parlamentares.", correta: false },
      { texto: "mediante empréstimos a serem quitados pelos municípios.", correta: false },
    ],
    explicacao:
      "O financiamento do SUAS adota a lógica fundo a fundo, com repasses regulares e automáticos organizados em blocos de financiamento (proteção social básica, especial e gestão), superando a lógica de convênios.",
    fonteLegal: "NOB-SUAS",
    palavrasChave: ["fundo a fundo", "blocos", "cofinanciamento"],
  },
  {
    assunto: A,
    subassunto: "Financiamento",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A gestão financeira do SUAS é operacionalizada por meio dos:",
    alternativas: [
      { texto: "fundos de assistência social, em cada esfera de governo.", correta: true },
      { texto: "orçamentos da seguridade previdenciária.", correta: false },
      { texto: "fundos de participação dos municípios.", correta: false },
      { texto: "fundos partidários.", correta: false },
      { texto: "recursos exclusivos de entidades privadas.", correta: false },
    ],
    explicacao:
      "Os recursos do SUAS são geridos pelos fundos de assistência social (nacional, estaduais, distrital e municipais), sob orientação e controle dos respectivos conselhos.",
    fonteLegal: "LOAS, art. 28; NOB-SUAS",
    palavrasChave: ["fundos", "FNAS", "financiamento"],
  },
  {
    assunto: A,
    subassunto: "Financiamento",
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "O Índice de Gestão Descentralizada (IGD) destina-se a:",
    alternativas: [
      { texto: "apoiar financeiramente o aprimoramento da gestão e a qualidade dos serviços/cadastros.", correta: true },
      { texto: "pagar diretamente os benefícios às famílias.", correta: false },
      { texto: "remunerar exclusivamente conselheiros.", correta: false },
      { texto: "custear obras de infraestrutura viária.", correta: false },
      { texto: "financiar campanhas eleitorais.", correta: false },
    ],
    explicacao:
      "O IGD (do SUAS e do Bolsa Família/Cadastro Único) mede a qualidade da gestão e, com base nele, são transferidos recursos para apoiar o aprimoramento da gestão descentralizada.",
    fonteLegal: "NOB-SUAS; legislação do IGD",
    palavrasChave: ["IGD", "gestão", "incentivo"],
  },
  {
    assunto: A,
    subassunto: "Vigilância socioassistencial",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A vigilância socioassistencial é responsável por:",
    alternativas: [
      { texto: "produzir e sistematizar informações sobre vulnerabilidades, riscos e a oferta de serviços.", correta: true },
      { texto: "fiscalizar e autuar entidades, com poder de polícia.", correta: false },
      { texto: "conceder benefícios de forma direta.", correta: false },
      { texto: "julgar recursos administrativos disciplinares.", correta: false },
      { texto: "controlar a arrecadação de tributos.", correta: false },
    ],
    explicacao:
      "A vigilância socioassistencial é uma das funções da assistência social, voltada à produção e sistematização de informações territorializadas sobre necessidades de proteção e sobre a rede de serviços.",
    fonteLegal: "NOB-SUAS; LOAS, art. 6º-A",
    palavrasChave: ["vigilância", "informação", "função"],
  },
  {
    assunto: A,
    subassunto: "Vigilância socioassistencial",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "São dimensões da vigilância socioassistencial:",
    alternativas: [
      { texto: "a vigilância das vulnerabilidades/riscos e a vigilância dos padrões de serviços ofertados.", correta: true },
      { texto: "a vigilância sanitária e a vigilância epidemiológica.", correta: false },
      { texto: "a vigilância patrimonial e a vigilância armada.", correta: false },
      { texto: "a vigilância fiscal e a tributária.", correta: false },
      { texto: "a vigilância ambiental e a fitossanitária.", correta: false },
    ],
    explicacao:
      "A vigilância socioassistencial atua em duas dimensões: a das situações de vulnerabilidade e risco das famílias/indivíduos e a do padrão e da capacidade de oferta dos serviços socioassistenciais.",
    fonteLegal: "NOB-SUAS",
    palavrasChave: ["dimensões", "vigilância", "serviços"],
  },
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O Pacto de Aprimoramento do SUAS é instrumento que:",
    alternativas: [
      { texto: "estabelece prioridades e metas de aprimoramento da gestão para estados, DF e municípios.", correta: true },
      { texto: "define o valor dos tributos municipais.", correta: false },
      { texto: "extingue os conselhos de assistência social.", correta: false },
      { texto: "concede aposentadorias especiais.", correta: false },
      { texto: "regula o sistema financeiro nacional.", correta: false },
    ],
    explicacao:
      "O Pacto de Aprimoramento do SUAS é o instrumento de planejamento pactuado que define prioridades e metas para o aprimoramento contínuo da gestão da política nos entes federados.",
    fonteLegal: "NOB-SUAS",
    palavrasChave: ["pacto", "metas", "aprimoramento"],
  },
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A gestão do trabalho no SUAS, conforme a NOB, pressupõe:",
    alternativas: [
      { texto: "equipes de referência compostas por servidores efetivos e política de educação permanente.", correta: true },
      { texto: "vedação à contratação de qualquer profissional.", correta: false },
      { texto: "trabalho exclusivamente voluntário.", correta: false },
      { texto: "ausência de qualquer composição mínima de equipe.", correta: false },
      { texto: "terceirização integral e obrigatória dos serviços.", correta: false },
    ],
    explicacao:
      "A NOB-SUAS e a NOB-RH preveem equipes de referência (composição mínima por porte e serviço), preferencialmente com servidores de carreira, e a educação permanente dos trabalhadores do SUAS.",
    fonteLegal: "NOB-SUAS; NOB-RH/SUAS",
    palavrasChave: ["equipes de referência", "educação permanente", "RH"],
  },
  {
    assunto: A,
    subassunto: "Financiamento",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Os pisos de proteção social, no financiamento do SUAS, correspondem a:",
    alternativas: [
      { texto: "parâmetros de transferência de recursos federais para o cofinanciamento dos serviços.", correta: true },
      { texto: "valores mínimos de benefícios pagos às famílias.", correta: false },
      { texto: "limites de gastos com pessoal.", correta: false },
      { texto: "tarifas cobradas dos usuários.", correta: false },
      { texto: "índices de correção de tributos.", correta: false },
    ],
    explicacao:
      "Os pisos de proteção social (básica e especial) são referências para a transferência de recursos federais aos demais entes, no cofinanciamento dos serviços socioassistenciais.",
    fonteLegal: "NOB-SUAS",
    palavrasChave: ["pisos", "cofinanciamento", "serviços"],
  },
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O comando único da política de assistência social, em cada esfera de governo, é exercido:",
    alternativas: [
      { texto: "pelo órgão gestor da assistência social (secretaria/ministério da área).", correta: true },
      { texto: "pelo conselho tutelar.", correta: false },
      { texto: "pelo Ministério Público.", correta: false },
      { texto: "por entidades privadas conveniadas.", correta: false },
      { texto: "pelo tribunal de contas.", correta: false },
    ],
    explicacao:
      "O comando único é exercido pelo órgão gestor da assistência social em cada esfera (ex.: a SEDES no DF), responsável pela coordenação da política no respectivo território.",
    fonteLegal: "LOAS; NOB-SUAS",
    palavrasChave: ["comando único", "órgão gestor"],
  },
  {
    assunto: A,
    subassunto: "Vigilância socioassistencial",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O Cadastro Único e os sistemas de informação do SUAS são, para a vigilância socioassistencial:",
    alternativas: [
      { texto: "fontes de dados essenciais para identificar vulnerabilidades e planejar a oferta.", correta: true },
      { texto: "instrumentos de cobrança de tributos.", correta: false },
      { texto: "ferramentas exclusivas da área da saúde.", correta: false },
      { texto: "registros sem relação com a gestão.", correta: false },
      { texto: "documentos de uso vedado à gestão pública.", correta: false },
    ],
    explicacao:
      "A vigilância socioassistencial utiliza o Cadastro Único e sistemas como o Censo SUAS e o RMA para conhecer o território, dimensionar demandas e planejar e qualificar a oferta de serviços.",
    fonteLegal: "NOB-SUAS",
    palavrasChave: ["Cadastro Único", "Censo SUAS", "informação"],
  },
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A responsabilidade primeira pela condução da política de assistência social é:",
    alternativas: [
      { texto: "do Estado, cabendo-lhe a primazia na condução em todos os níveis.", correta: true },
      { texto: "das entidades privadas filantrópicas.", correta: false },
      { texto: "das famílias beneficiárias.", correta: false },
      { texto: "das organizações internacionais.", correta: false },
      { texto: "do mercado.", correta: false },
    ],
    explicacao:
      "Tanto a LOAS quanto a NOB-SUAS afirmam a primazia da responsabilidade do Estado na condução da política de assistência social em cada esfera de governo.",
    fonteLegal: "LOAS, art. 5º; NOB-SUAS",
    palavrasChave: ["primazia do Estado", "condução"],
  },
  {
    assunto: A,
    subassunto: "Financiamento",
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A condição para que um ente receba recursos federais regulares do SUAS inclui:",
    alternativas: [
      { texto: "ter conselho, fundo e plano de assistência social, com alocação de recursos próprios.", correta: true },
      { texto: "comprovar superávit primário.", correta: false },
      { texto: "possuir frota de veículos própria.", correta: false },
      { texto: "ter população superior a um milhão de habitantes.", correta: false },
      { texto: "renunciar a qualquer controle social.", correta: false },
    ],
    explicacao:
      "Para habilitar-se à gestão e ao cofinanciamento, o ente deve constituir conselho, fundo e plano de assistência social, além de alocar recursos próprios no respectivo fundo — o tripé exigido pela LOAS/NOB.",
    fonteLegal: "LOAS, art. 30; NOB-SUAS",
    palavrasChave: ["conselho", "fundo", "plano"],
  },
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O Censo SUAS é um instrumento que:",
    alternativas: [
      { texto: "coleta anualmente informações sobre os serviços, unidades, conselhos e gestão do SUAS.", correta: true },
      { texto: "realiza o recenseamento demográfico nacional.", correta: false },
      { texto: "fiscaliza o pagamento de tributos.", correta: false },
      { texto: "concede benefícios eventuais.", correta: false },
      { texto: "substitui o Cadastro Único.", correta: false },
    ],
    explicacao:
      "O Censo SUAS é uma coleta anual de informações sobre a estrutura e o funcionamento das unidades (CRAS, CREAS etc.), conselhos e gestão, subsidiando a vigilância socioassistencial e o monitoramento.",
    fonteLegal: "NOB-SUAS",
    palavrasChave: ["Censo SUAS", "monitoramento"],
  },
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A relação entre as esferas de governo no SUAS é marcada pela:",
    alternativas: [
      { texto: "cooperação federativa, com competências partilhadas e descentralização.", correta: true },
      { texto: "subordinação hierárquica dos municípios à União.", correta: false },
      { texto: "independência absoluta sem qualquer articulação.", correta: false },
      { texto: "centralização total no governo federal.", correta: false },
      { texto: "transferência da gestão a empresas privadas.", correta: false },
    ],
    explicacao:
      "O SUAS funda-se na cooperação federativa, com competências partilhadas entre União, estados, DF e municípios e gestão descentralizada e participativa.",
    fonteLegal: "NOB-SUAS; CF/1988",
    palavrasChave: ["cooperação federativa", "descentralização"],
  },
  {
    assunto: A,
    subassunto: "Vigilância socioassistencial",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O Relatório Mensal de Atendimentos (RMA) tem por objetivo:",
    alternativas: [
      { texto: "registrar o volume e o perfil dos atendimentos realizados por CRAS e CREAS.", correta: true },
      { texto: "calcular o imposto devido pelas famílias.", correta: false },
      { texto: "definir a folha de pagamento dos servidores.", correta: false },
      { texto: "substituir os planos de assistência social.", correta: false },
      { texto: "registrar internações hospitalares.", correta: false },
    ],
    explicacao:
      "O RMA registra mensalmente os atendimentos e o volume de serviços ofertados nas unidades (CRAS/CREAS), alimentando a vigilância socioassistencial e o monitoramento da política.",
    fonteLegal: "NOB-SUAS",
    palavrasChave: ["RMA", "atendimentos", "monitoramento"],
  },
  {
    assunto: A,
    subassunto: "Financiamento",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Os recursos do cofinanciamento federal dos serviços do SUAS, quando não executados, em regra:",
    alternativas: [
      { texto: "podem ser reprogramados, mantendo-se vinculados à finalidade da assistência social.", correta: true },
      { texto: "devem ser destinados a qualquer área do orçamento.", correta: false },
      { texto: "são automaticamente convertidos em receita tributária.", correta: false },
      { texto: "pertencem às entidades privadas conveniadas.", correta: false },
      { texto: "podem ser usados para campanhas publicitárias do gestor.", correta: false },
    ],
    explicacao:
      "Os saldos dos recursos do cofinanciamento permanecem vinculados ao fundo de assistência social e à sua finalidade, podendo ser reprogramados conforme as regras do SUAS, sob controle do conselho.",
    fonteLegal: "NOB-SUAS",
    palavrasChave: ["reprogramação", "vinculação", "fundo"],
  },
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A territorialização da gestão no SUAS implica que o planejamento da oferta deve:",
    alternativas: [
      { texto: "considerar a distribuição das vulnerabilidades e a localização da rede no território.", correta: true },
      { texto: "ignorar as desigualdades intraurbanas.", correta: false },
      { texto: "padronizar a oferta sem considerar o território.", correta: false },
      { texto: "concentrar serviços apenas nas áreas centrais.", correta: false },
      { texto: "desconsiderar dados da vigilância socioassistencial.", correta: false },
    ],
    explicacao:
      "A gestão territorializada exige planejar a oferta a partir do conhecimento das vulnerabilidades e da rede disponível em cada território, orientada pela vigilância socioassistencial.",
    fonteLegal: "NOB-SUAS; PNAS/2004",
    palavrasChave: ["territorialização", "planejamento", "oferta"],
  },
  {
    assunto: A,
    subassunto: "Gestão",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "No Distrito Federal, a gestão do SUAS apresenta a peculiaridade de:",
    alternativas: [
      { texto: "acumular competências estaduais e municipais, por sua natureza de ente federativo único.", correta: true },
      { texto: "não participar do SUAS.", correta: false },
      { texto: "depender exclusivamente de convênios com Goiás.", correta: false },
      { texto: "ter gestão exercida pela União.", correta: false },
      { texto: "estar dispensado de constituir fundo e conselho.", correta: false },
    ],
    explicacao:
      "Por não ser dividido em municípios, o DF acumula as competências estaduais e municipais na gestão do SUAS, organizando a política por meio do seu órgão gestor (a SEDES).",
    fonteLegal: "CF/1988, art. 32; NOB-SUAS",
    palavrasChave: ["Distrito Federal", "competências", "SEDES"],
  },
];

export default questoes;
