import type { QSeed } from "./tipos";

const A = "PDPM";

const questoes: QSeed[] = [
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A Política Distrital para as Mulheres (PDPM) tem como objetivo central:",
    alternativas: [
      { texto: "promover a igualdade de gênero e os direitos das mulheres no Distrito Federal.", correta: true },
      { texto: "regular o regime jurídico dos servidores do DF.", correta: false },
      { texto: "organizar o sistema tributário distrital.", correta: false },
      { texto: "disciplinar o transporte público coletivo.", correta: false },
      { texto: "definir o plano diretor de ordenamento territorial.", correta: false },
    ],
    explicacao:
      "A PDPM é a política pública do DF voltada à promoção da igualdade de gênero, à garantia e ampliação dos direitos das mulheres e ao enfrentamento das desigualdades e violências de gênero.",
    fonteLegal: "Política Distrital para as Mulheres (DF)",
    palavrasChave: ["igualdade de gênero", "direitos das mulheres"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A transversalidade de gênero, como diretriz da PDPM, significa que:",
    alternativas: [
      { texto: "a perspectiva de gênero deve permear o conjunto das políticas públicas, e não apenas ações isoladas.", correta: true },
      { texto: "apenas um órgão deve cuidar das questões das mulheres, isoladamente.", correta: false },
      { texto: "as ações para mulheres devem ser pontuais e desarticuladas.", correta: false },
      { texto: "as políticas de gênero substituem as demais políticas públicas.", correta: false },
      { texto: "a temática de gênero deve ser tratada apenas na segurança pública.", correta: false },
    ],
    explicacao:
      "A transversalidade de gênero pressupõe incorporar a perspectiva de gênero em todas as políticas públicas (saúde, educação, trabalho, assistência etc.), de forma articulada e intersetorial.",
    fonteLegal: "PDPM (DF); diretrizes de política para mulheres",
    palavrasChave: ["transversalidade", "intersetorialidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "São eixos comumente associados às políticas para as mulheres, como a PDPM:",
    alternativas: [
      { texto: "autonomia econômica, enfrentamento à violência e participação política das mulheres.", correta: true },
      { texto: "arrecadação tributária e dívida pública.", correta: false },
      { texto: "licitações e contratos administrativos.", correta: false },
      { texto: "ordenamento do trânsito e mobilidade.", correta: false },
      { texto: "regulação do sistema financeiro.", correta: false },
    ],
    explicacao:
      "As políticas para mulheres costumam organizar-se em eixos como autonomia econômica e igualdade no trabalho, enfrentamento a todas as formas de violência e fortalecimento da participação social e política das mulheres.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["eixos", "autonomia econômica", "enfrentamento à violência"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O enfrentamento à violência contra a mulher, no âmbito da PDPM, articula-se com:",
    alternativas: [
      { texto: "a rede de proteção e a Lei Maria da Penha.", correta: true },
      { texto: "a política de defesa do consumidor, exclusivamente.", correta: false },
      { texto: "o licenciamento ambiental.", correta: false },
      { texto: "a regulação de preços de combustíveis.", correta: false },
      { texto: "o sistema penitenciário federal, apenas.", correta: false },
    ],
    explicacao:
      "O enfrentamento à violência integra a PDPM e dialoga com a Lei Maria da Penha e com a rede de proteção (saúde, assistência social, segurança e justiça), de forma intersetorial.",
    fonteLegal: "PDPM (DF); Lei 11.340/2006",
    palavrasChave: ["enfrentamento", "rede de proteção", "Maria da Penha"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A autonomia econômica das mulheres, como objetivo da PDPM, busca:",
    alternativas: [
      { texto: "ampliar o acesso das mulheres ao trabalho, à renda e à qualificação profissional.", correta: true },
      { texto: "restringir a participação das mulheres no mercado de trabalho.", correta: false },
      { texto: "vincular o atendimento à contribuição previdenciária.", correta: false },
      { texto: "limitar o acesso a crédito e empreendedorismo.", correta: false },
      { texto: "transferir a renda apenas a homens chefes de família.", correta: false },
    ],
    explicacao:
      "A promoção da autonomia econômica visa ampliar o acesso das mulheres ao trabalho digno, à renda, ao crédito, ao empreendedorismo e à qualificação, reduzindo desigualdades de gênero.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["autonomia econômica", "trabalho", "renda"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A coordenação das políticas para as mulheres no DF é exercida, prioritariamente, por:",
    alternativas: [
      { texto: "órgão governamental responsável pelas políticas das mulheres, articulado às demais pastas.", correta: true },
      { texto: "uma entidade privada com fins lucrativos.", correta: false },
      { texto: "o Tribunal de Contas do DF.", correta: false },
      { texto: "uma organização internacional.", correta: false },
      { texto: "o Ministério Público, em caráter executivo.", correta: false },
    ],
    explicacao:
      "As políticas para as mulheres são coordenadas por órgão governamental específico (no DF, vinculado à estrutura da SEDES/Secretaria da Mulher), com atuação articulada e intersetorial.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["coordenação", "órgão gestor"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A participação social das mulheres na construção da PDPM ocorre, tipicamente, por meio de:",
    alternativas: [
      { texto: "conferências e conselhos dos direitos das mulheres.", correta: true },
      { texto: "decisões exclusivas do Poder Executivo, sem consulta.", correta: false },
      { texto: "deliberações de empresas privadas.", correta: false },
      { texto: "consultas restritas a órgãos de fiscalização tributária.", correta: false },
      { texto: "processos sem qualquer participação social.", correta: false },
    ],
    explicacao:
      "A construção e o monitoramento das políticas para mulheres contam com instâncias de participação social, como conferências e conselhos dos direitos da mulher, fortalecendo o controle social.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["participação social", "conselhos", "conferências"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A interseccionalidade, no contexto das políticas para mulheres, refere-se a:",
    alternativas: [
      { texto: "considerar a sobreposição de marcadores como raça, classe, deficiência e território nas desigualdades de gênero.", correta: true },
      { texto: "tratar todas as mulheres como grupo homogêneo.", correta: false },
      { texto: "ignorar as desigualdades raciais.", correta: false },
      { texto: "restringir a política a um único território.", correta: false },
      { texto: "desconsiderar as mulheres com deficiência.", correta: false },
    ],
    explicacao:
      "A interseccionalidade reconhece que as desigualdades de gênero se combinam com raça, classe, deficiência, idade e território, exigindo respostas específicas para os diferentes grupos de mulheres.",
    fonteLegal: "PDPM (DF); abordagem de gênero",
    palavrasChave: ["interseccionalidade", "raça", "classe"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "São públicos prioritários das ações da PDPM:",
    alternativas: [
      { texto: "mulheres em situação de violência e de vulnerabilidade social.", correta: true },
      { texto: "exclusivamente grandes empresárias.", correta: false },
      { texto: "apenas servidoras públicas do DF.", correta: false },
      { texto: "somente mulheres com ensino superior.", correta: false },
      { texto: "apenas turistas em trânsito no DF.", correta: false },
    ],
    explicacao:
      "As ações priorizam mulheres em situação de violência, pobreza e vulnerabilidade social, com atenção a grupos historicamente discriminados.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["público prioritário", "vulnerabilidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A articulação da PDPM com a política de assistência social (SUAS) é importante porque:",
    alternativas: [
      { texto: "a rede socioassistencial (CRAS/CREAS) acolhe e acompanha mulheres em situação de vulnerabilidade e violência.", correta: true },
      { texto: "a assistência social substitui integralmente a segurança pública.", correta: false },
      { texto: "a PDPM impede o atendimento de mulheres nos CRAS.", correta: false },
      { texto: "o SUAS é destinado apenas a homens.", correta: false },
      { texto: "não há qualquer relação entre as políticas.", correta: false },
    ],
    explicacao:
      "A rede do SUAS (CRAS e CREAS) é fundamental para acolher, acompanhar e encaminhar mulheres em situação de vulnerabilidade e violência, integrando a PDPM à proteção social.",
    fonteLegal: "PDPM (DF); PNAS/2004",
    palavrasChave: ["SUAS", "CREAS", "rede"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "O monitoramento e a avaliação da PDPM têm por finalidade:",
    alternativas: [
      { texto: "verificar o cumprimento das metas e qualificar as ações de promoção dos direitos das mulheres.", correta: true },
      { texto: "punir as mulheres beneficiárias por descumprimento de metas.", correta: false },
      { texto: "extinguir os conselhos de direitos.", correta: false },
      { texto: "transferir a política para a iniciativa privada.", correta: false },
      { texto: "limitar o acesso à informação.", correta: false },
    ],
    explicacao:
      "O monitoramento e a avaliação permitem acompanhar metas e resultados, identificar lacunas e aprimorar as ações da política, com transparência e participação social.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["monitoramento", "avaliação", "metas"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A igualdade de gênero, princípio da PDPM, opõe-se a:",
    alternativas: [
      { texto: "discriminações e desigualdades estruturais entre homens e mulheres.", correta: true },
      { texto: "qualquer política pública de saúde.", correta: false },
      { texto: "à existência de conselhos de direitos.", correta: false },
      { texto: "ao princípio da dignidade da pessoa humana.", correta: false },
      { texto: "à participação social.", correta: false },
    ],
    explicacao:
      "A igualdade de gênero busca enfrentar as discriminações e desigualdades estruturais entre homens e mulheres, promovendo equidade de oportunidades e direitos.",
    fonteLegal: "PDPM (DF); CF/1988, art. 5º, I",
    palavrasChave: ["igualdade de gênero", "equidade"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A oferta de acolhimento a mulheres vítimas de violência com risco de morte pode incluir:",
    alternativas: [
      { texto: "casas-abrigo e serviços de acolhimento sigilosos.", correta: true },
      { texto: "apenas atendimento por telefone.", correta: false },
      { texto: "exposição pública da identidade da vítima.", correta: false },
      { texto: "encaminhamento ao agressor.", correta: false },
      { texto: "cobrança de taxas da vítima.", correta: false },
    ],
    explicacao:
      "Mulheres em risco de morte podem ser acolhidas em casas-abrigo e serviços de acolhimento sigiloso, que garantem proteção, segurança e atendimento multidisciplinar.",
    fonteLegal: "PDPM (DF); Lei 11.340/2006",
    palavrasChave: ["casa-abrigo", "sigilo", "proteção"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A capacitação de profissionais da rede para o atendimento humanizado às mulheres é:",
    alternativas: [
      { texto: "uma ação de qualificação que integra a política para as mulheres.", correta: true },
      { texto: "uma penalidade aplicada aos servidores.", correta: false },
      { texto: "uma medida de arrecadação.", correta: false },
      { texto: "vedada pela legislação.", correta: false },
      { texto: "restrita a empresas privadas.", correta: false },
    ],
    explicacao:
      "A capacitação e a sensibilização de profissionais (saúde, assistência, segurança e justiça) qualificam o atendimento humanizado e o funcionamento da rede de enfrentamento à violência.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["capacitação", "atendimento humanizado"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A PDPM, ao tratar de direitos sexuais e reprodutivos, busca:",
    alternativas: [
      { texto: "ampliar o acesso das mulheres à informação e aos serviços de saúde relacionados.", correta: true },
      { texto: "restringir o acesso a serviços de saúde da mulher.", correta: false },
      { texto: "condicionar o atendimento ao pagamento de taxas.", correta: false },
      { texto: "excluir as mulheres das políticas de saúde.", correta: false },
      { texto: "transferir esses direitos à iniciativa privada.", correta: false },
    ],
    explicacao:
      "A política reconhece os direitos sexuais e reprodutivos das mulheres, buscando ampliar o acesso à informação e aos serviços de saúde, em articulação com o SUS.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["direitos reprodutivos", "saúde da mulher"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A divulgação de informações sobre os serviços de proteção à mulher é importante porque:",
    alternativas: [
      { texto: "facilita o acesso das mulheres à rede de atendimento e a canais de denúncia.", correta: true },
      { texto: "substitui a necessidade de delegacias especializadas.", correta: false },
      { texto: "é vedada pela política.", correta: false },
      { texto: "destina-se apenas a profissionais.", correta: false },
      { texto: "tem caráter sigiloso e restrito.", correta: false },
    ],
    explicacao:
      "Informar sobre serviços e canais (como o Ligue 180) amplia o acesso das mulheres à rede de proteção e estimula denúncias, sendo ação relevante da política.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["informação", "Ligue 180", "acesso"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A perspectiva de gênero nos orçamentos públicos (orçamento sensível a gênero) consiste em:",
    alternativas: [
      { texto: "alocar e monitorar recursos considerando os impactos diferenciados sobre mulheres e homens.", correta: true },
      { texto: "eliminar o orçamento das políticas sociais.", correta: false },
      { texto: "destinar recursos apenas a obras viárias.", correta: false },
      { texto: "vedar gastos com políticas para mulheres.", correta: false },
      { texto: "restringir a transparência orçamentária.", correta: false },
    ],
    explicacao:
      "O orçamento sensível a gênero busca planejar, alocar e monitorar recursos públicos considerando os impactos diferenciados das políticas sobre mulheres e homens, promovendo equidade.",
    fonteLegal: "PDPM (DF); diretrizes de gênero",
    palavrasChave: ["orçamento", "gênero", "equidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A atuação intersetorial da PDPM significa que o enfrentamento das desigualdades de gênero deve envolver:",
    alternativas: [
      { texto: "diferentes secretarias e políticas (saúde, educação, trabalho, segurança, assistência).", correta: true },
      { texto: "apenas a Secretaria da Mulher, isoladamente.", correta: false },
      { texto: "somente o sistema de justiça.", correta: false },
      { texto: "exclusivamente entidades privadas.", correta: false },
      { texto: "apenas organismos internacionais.", correta: false },
    ],
    explicacao:
      "A intersetorialidade é central: o enfrentamento das desigualdades de gênero requer ação coordenada entre múltiplas secretarias e políticas públicas.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["intersetorialidade", "coordenação"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O combate à feminização da pobreza, objetivo presente nas políticas para mulheres, relaciona-se a:",
    alternativas: [
      { texto: "reduzir a maior incidência da pobreza entre mulheres, especialmente chefes de família.", correta: true },
      { texto: "aumentar a desigualdade de renda entre os gêneros.", correta: false },
      { texto: "excluir as mulheres dos programas sociais.", correta: false },
      { texto: "restringir a transferência de renda a homens.", correta: false },
      { texto: "ignorar as famílias monoparentais femininas.", correta: false },
    ],
    explicacao:
      "A feminização da pobreza expressa a maior vulnerabilidade econômica das mulheres, sobretudo as chefes de família monoparental; as políticas buscam reduzir essa desigualdade por meio de renda, trabalho e proteção social.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["feminização da pobreza", "chefia familiar"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A garantia de creches e equipamentos de cuidado é relevante para a PDPM porque:",
    alternativas: [
      { texto: "favorece a autonomia das mulheres e sua inserção no trabalho e na educação.", correta: true },
      { texto: "não tem relação com a igualdade de gênero.", correta: false },
      { texto: "destina-se exclusivamente aos homens.", correta: false },
      { texto: "reduz os direitos das crianças.", correta: false },
      { texto: "é vedada pela política.", correta: false },
    ],
    explicacao:
      "A divisão desigual do trabalho de cuidado recai sobre as mulheres; ampliar creches e equipamentos de cuidado contribui para sua autonomia, inserção no trabalho e continuidade dos estudos.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["cuidado", "creche", "autonomia"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A produção de dados e estatísticas desagregados por sexo serve para:",
    alternativas: [
      { texto: "subsidiar o diagnóstico das desigualdades e o planejamento das políticas para mulheres.", correta: true },
      { texto: "ocultar as desigualdades de gênero.", correta: false },
      { texto: "substituir a participação social.", correta: false },
      { texto: "impedir a avaliação das políticas.", correta: false },
      { texto: "restringir o acesso à informação pública.", correta: false },
    ],
    explicacao:
      "Dados desagregados por sexo (e outros marcadores) permitem dimensionar as desigualdades e fundamentar o planejamento, o monitoramento e a avaliação das políticas para mulheres.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["dados", "estatísticas", "diagnóstico"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A articulação entre a PDPM e a Lei Maria da Penha evidencia que a política distrital:",
    alternativas: [
      { texto: "operacionaliza, no território do DF, ações de prevenção e enfrentamento previstas na legislação federal.", correta: true },
      { texto: "revoga a Lei Maria da Penha no DF.", correta: false },
      { texto: "afasta a competência da União sobre o tema.", correta: false },
      { texto: "restringe a aplicação da lei federal.", correta: false },
      { texto: "substitui o Judiciário no julgamento dos casos.", correta: false },
    ],
    explicacao:
      "A política distrital complementa e operacionaliza, no território, as diretrizes da legislação federal (como a Lei Maria da Penha), organizando a rede local de prevenção, atendimento e enfrentamento.",
    fonteLegal: "PDPM (DF); Lei 11.340/2006",
    palavrasChave: ["articulação", "competência", "rede local"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A promoção da participação política das mulheres busca:",
    alternativas: [
      { texto: "ampliar a presença e a influência das mulheres nos espaços de poder e decisão.", correta: true },
      { texto: "reduzir a representação feminina na política.", correta: false },
      { texto: "restringir o direito ao voto.", correta: false },
      { texto: "vedar a candidatura de mulheres.", correta: false },
      { texto: "limitar a atuação em conselhos.", correta: false },
    ],
    explicacao:
      "Um dos eixos das políticas para mulheres é o fortalecimento da participação e da representação feminina nos espaços de poder e decisão, enfrentando a sub-representação histórica.",
    fonteLegal: "PDPM (DF)",
    palavrasChave: ["participação política", "representação"],
  },
];

export default questoes;
