import type { QSeed } from "./tipos";

const A = "Plano DF Social";

const questoes: QSeed[] = [
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O Plano DF Social é, em essência, uma estratégia do Governo do Distrito Federal voltada a:",
    alternativas: [
      { texto: "articular ações e programas de proteção e desenvolvimento social para enfrentar a pobreza e a vulnerabilidade.", correta: true },
      { texto: "regular o transporte público do DF.", correta: false },
      { texto: "organizar o regime jurídico dos servidores.", correta: false },
      { texto: "disciplinar o uso do solo urbano.", correta: false },
      { texto: "definir a política de segurança pública.", correta: false },
    ],
    explicacao:
      "O Plano DF Social é uma estratégia de articulação de programas e ações de proteção social e desenvolvimento social no DF, com foco no enfrentamento da pobreza e das vulnerabilidades sociais.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["proteção social", "pobreza", "vulnerabilidade"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O órgão gestor responsável pela coordenação do Plano DF Social é, prioritariamente:",
    alternativas: [
      { texto: "a Secretaria de Estado de Desenvolvimento Social do DF (SEDES).", correta: true },
      { texto: "a Secretaria de Fazenda.", correta: false },
      { texto: "a Secretaria de Transportes.", correta: false },
      { texto: "o Tribunal de Contas do DF.", correta: false },
      { texto: "uma entidade privada com fins lucrativos.", correta: false },
    ],
    explicacao:
      "A coordenação do Plano DF Social cabe à SEDES, órgão gestor da política de desenvolvimento e assistência social do Distrito Federal, em articulação com outras pastas.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["SEDES", "coordenação"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O Cadastro Único (CadÚnico) cumpre, no Plano DF Social, a função de:",
    alternativas: [
      { texto: "identificar e caracterizar as famílias de baixa renda para acesso a programas sociais.", correta: true },
      { texto: "calcular tributos das famílias.", correta: false },
      { texto: "registrar infrações de trânsito.", correta: false },
      { texto: "controlar a folha de pagamento dos servidores.", correta: false },
      { texto: "cadastrar empresas para licitação.", correta: false },
    ],
    explicacao:
      "O CadÚnico é o instrumento de identificação e caracterização socioeconômica das famílias de baixa renda, base para a seleção de beneficiários dos programas sociais articulados pelo Plano DF Social.",
    fonteLegal: "Plano DF Social; Decreto federal do Cadastro Único",
    palavrasChave: ["Cadastro Único", "baixa renda", "elegibilidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "São exemplos de programas que podem integrar a rede de proteção articulada pelo Plano DF Social:",
    alternativas: [
      { texto: "Cartão Prato Cheio, Cartão Gás, restaurantes comunitários e benefícios eventuais.", correta: true },
      { texto: "licenciamento ambiental e zoneamento.", correta: false },
      { texto: "concursos públicos e estágio probatório.", correta: false },
      { texto: "fiscalização tributária e dívida ativa.", correta: false },
      { texto: "obras de mobilidade urbana.", correta: false },
    ],
    explicacao:
      "O Plano DF Social articula programas de transferência de renda e segurança alimentar (como Cartão Prato Cheio e Cartão Gás), restaurantes comunitários e benefícios eventuais, entre outras ações de proteção social.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["programas", "segurança alimentar", "transferência de renda"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A intersetorialidade é central no Plano DF Social porque:",
    alternativas: [
      { texto: "o enfrentamento da pobreza exige a atuação articulada de assistência, saúde, educação, trabalho e segurança alimentar.", correta: true },
      { texto: "cada secretaria deve atuar isoladamente.", correta: false },
      { texto: "apenas a saúde é responsável pelo plano.", correta: false },
      { texto: "a iniciativa privada deve substituir o Estado.", correta: false },
      { texto: "a articulação entre políticas é proibida.", correta: false },
    ],
    explicacao:
      "O Plano DF Social adota a lógica intersetorial: a superação da pobreza e da vulnerabilidade demanda ações coordenadas de diferentes políticas públicas.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["intersetorialidade", "articulação"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O público prioritário do Plano DF Social é composto por:",
    alternativas: [
      { texto: "famílias em situação de pobreza, extrema pobreza e vulnerabilidade social.", correta: true },
      { texto: "apenas servidores públicos do DF.", correta: false },
      { texto: "exclusivamente grandes empresas.", correta: false },
      { texto: "somente turistas.", correta: false },
      { texto: "apenas famílias de alta renda.", correta: false },
    ],
    explicacao:
      "O foco do Plano DF Social são as famílias em situação de pobreza, extrema pobreza e vulnerabilidade social, identificadas, em regra, pelo Cadastro Único.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["público prioritário", "extrema pobreza"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A segurança alimentar e nutricional, no âmbito do Plano DF Social, é promovida por meio de:",
    alternativas: [
      { texto: "programas como restaurantes comunitários e transferência de renda para alimentação.", correta: true },
      { texto: "exclusivamente multas a estabelecimentos.", correta: false },
      { texto: "apenas campanhas publicitárias.", correta: false },
      { texto: "somente importação de alimentos.", correta: false },
      { texto: "vedação ao acesso a alimentos.", correta: false },
    ],
    explicacao:
      "A segurança alimentar e nutricional é promovida por ações como restaurantes comunitários, Cartão Prato Cheio e demais iniciativas que ampliam o acesso a alimentação adequada.",
    fonteLegal: "Plano DF Social; LOSAN (Lei 11.346/2006)",
    palavrasChave: ["segurança alimentar", "acesso a alimentos"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A geração de trabalho e renda, como eixo do Plano DF Social, busca:",
    alternativas: [
      { texto: "promover a autonomia das famílias por meio de qualificação, emprego e empreendedorismo.", correta: true },
      { texto: "manter as famílias permanentemente dependentes de benefícios.", correta: false },
      { texto: "reduzir o acesso ao mercado de trabalho.", correta: false },
      { texto: "vedar a qualificação profissional.", correta: false },
      { texto: "transferir renda apenas a empresas.", correta: false },
    ],
    explicacao:
      "Além da proteção imediata, o Plano DF Social busca a emancipação das famílias por meio de qualificação profissional, inclusão produtiva, emprego e apoio ao empreendedorismo.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["trabalho e renda", "inclusão produtiva", "emancipação"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A lógica de 'porta de entrada' única e de encaminhamento integrado, presente no Plano DF Social, apoia-se sobretudo:",
    alternativas: [
      { texto: "na rede do SUAS (CRAS e CREAS) e no Cadastro Único para acolher e direcionar as famílias.", correta: true },
      { texto: "exclusivamente em delegacias de polícia.", correta: false },
      { texto: "apenas em hospitais de alta complexidade.", correta: false },
      { texto: "em órgãos de arrecadação tributária.", correta: false },
      { texto: "em entidades privadas com fins lucrativos.", correta: false },
    ],
    explicacao:
      "A rede do SUAS (especialmente os CRAS) e o Cadastro Único funcionam como portas de entrada e instrumentos de encaminhamento integrado das famílias aos programas do Plano DF Social.",
    fonteLegal: "Plano DF Social; PNAS/2004",
    palavrasChave: ["porta de entrada", "CRAS", "encaminhamento"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O Plano DF Social tem caráter:",
    alternativas: [
      { texto: "de política pública de proteção social, articulada e voltada à redução das desigualdades.", correta: true },
      { texto: "de programa exclusivamente assistencialista e temporário.", correta: false },
      { texto: "de ação privada sem participação do Estado.", correta: false },
      { texto: "de política tributária.", correta: false },
      { texto: "de regulação do mercado financeiro.", correta: false },
    ],
    explicacao:
      "O Plano DF Social estrutura-se como política pública de proteção e desenvolvimento social, articulando programas para reduzir desigualdades e promover direitos, e não como mero assistencialismo pontual.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["política pública", "desigualdades"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A focalização dos programas do Plano DF Social, baseada em critérios de renda, tem por objetivo:",
    alternativas: [
      { texto: "direcionar os recursos a quem mais necessita, priorizando as famílias mais pobres.", correta: true },
      { texto: "beneficiar prioritariamente famílias de alta renda.", correta: false },
      { texto: "distribuir benefícios sem qualquer critério.", correta: false },
      { texto: "excluir as famílias em extrema pobreza.", correta: false },
      { texto: "vincular o acesso à contribuição previdenciária.", correta: false },
    ],
    explicacao:
      "A focalização por critérios de renda (via CadÚnico) busca direcionar os recursos públicos às famílias em maior situação de pobreza e vulnerabilidade, ampliando a efetividade da política.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["focalização", "renda", "priorização"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O monitoramento e a avaliação do Plano DF Social permitem:",
    alternativas: [
      { texto: "acompanhar resultados, corrigir rumos e qualificar a gestão dos programas sociais.", correta: true },
      { texto: "ocultar os resultados das ações.", correta: false },
      { texto: "extinguir a participação social.", correta: false },
      { texto: "impedir a transparência das informações.", correta: false },
      { texto: "punir as famílias beneficiárias.", correta: false },
    ],
    explicacao:
      "O monitoramento e a avaliação são essenciais para medir resultados, identificar falhas e aprimorar a gestão e a efetividade dos programas sociais articulados pelo plano.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["monitoramento", "avaliação", "gestão"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A proteção social no Plano DF Social dialoga diretamente com a:",
    alternativas: [
      { texto: "Política Nacional de Assistência Social (PNAS) e o SUAS.", correta: true },
      { texto: "política industrial de exportação.", correta: false },
      { texto: "regulação de telecomunicações.", correta: false },
      { texto: "política monetária nacional.", correta: false },
      { texto: "legislação de propriedade intelectual.", correta: false },
    ],
    explicacao:
      "As ações de proteção social do Plano DF Social alinham-se à PNAS e ao SUAS, utilizando a rede socioassistencial e seus instrumentos para alcançar as famílias.",
    fonteLegal: "Plano DF Social; PNAS/2004",
    palavrasChave: ["PNAS", "SUAS", "proteção social"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A articulação entre transferência de renda e acompanhamento familiar no Plano DF Social visa:",
    alternativas: [
      { texto: "combinar alívio imediato da pobreza com o fortalecimento dos vínculos e o acesso a direitos.", correta: true },
      { texto: "substituir todos os serviços socioassistenciais pela renda.", correta: false },
      { texto: "eliminar o trabalho social com famílias.", correta: false },
      { texto: "tornar a renda a única ação da política.", correta: false },
      { texto: "desestimular o acesso a outros direitos.", correta: false },
    ],
    explicacao:
      "A combinação de transferência de renda com acompanhamento familiar (PAIF/PAEFI) busca aliviar a pobreza no curto prazo e, ao mesmo tempo, fortalecer vínculos e promover acesso a direitos e à emancipação.",
    fonteLegal: "Plano DF Social; PNAS/2004",
    palavrasChave: ["transferência de renda", "acompanhamento familiar"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A participação e o controle social sobre o Plano DF Social são exercidos, sobretudo, por:",
    alternativas: [
      { texto: "conselhos de políticas públicas (como o de assistência social) e instâncias de participação.", correta: true },
      { texto: "decisões sigilosas, sem qualquer controle.", correta: false },
      { texto: "empresas privadas contratadas.", correta: false },
      { texto: "órgãos de arrecadação tributária.", correta: false },
      { texto: "organismos internacionais, exclusivamente.", correta: false },
    ],
    explicacao:
      "O controle social ocorre por meio de conselhos de políticas públicas (como o Conselho de Assistência Social do DF) e demais instâncias participativas, garantindo transparência e accountability.",
    fonteLegal: "Plano DF Social; LOAS",
    palavrasChave: ["controle social", "conselhos"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Entre os objetivos do Plano DF Social, destaca-se:",
    alternativas: [
      { texto: "reduzir a pobreza e a desigualdade social no Distrito Federal.", correta: true },
      { texto: "aumentar a carga tributária das famílias pobres.", correta: false },
      { texto: "restringir o acesso a programas sociais.", correta: false },
      { texto: "concentrar renda.", correta: false },
      { texto: "privatizar a assistência social.", correta: false },
    ],
    explicacao:
      "Um objetivo central do plano é reduzir a pobreza e a desigualdade social, promovendo proteção social e oportunidades de desenvolvimento às famílias vulneráveis.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["redução da pobreza", "desigualdade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O combate à fome e à insegurança alimentar, no Plano DF Social, é tratado como:",
    alternativas: [
      { texto: "prioridade, por meio de ações de segurança alimentar e nutricional.", correta: true },
      { texto: "tema irrelevante para a política social.", correta: false },
      { texto: "responsabilidade exclusiva das famílias.", correta: false },
      { texto: "assunto restrito à iniciativa privada.", correta: false },
      { texto: "questão de competência da política de trânsito.", correta: false },
    ],
    explicacao:
      "O enfrentamento da fome e da insegurança alimentar é prioridade do plano, materializado em programas de segurança alimentar e nutricional (restaurantes comunitários, Prato Cheio etc.).",
    fonteLegal: "Plano DF Social; LOSAN",
    palavrasChave: ["fome", "insegurança alimentar"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A integração de bases de dados e sistemas no Plano DF Social contribui para:",
    alternativas: [
      { texto: "qualificar a identificação das famílias e evitar sobreposição ou lacunas no atendimento.", correta: true },
      { texto: "dificultar o acesso das famílias aos programas.", correta: false },
      { texto: "aumentar a fragmentação das ações.", correta: false },
      { texto: "eliminar o Cadastro Único.", correta: false },
      { texto: "restringir o planejamento.", correta: false },
    ],
    explicacao:
      "A integração de dados (CadÚnico e sistemas setoriais) melhora a identificação das famílias, reduz duplicidades e lacunas e qualifica o planejamento e a oferta dos programas.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["integração de dados", "planejamento"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A territorialização das ações do Plano DF Social significa considerar:",
    alternativas: [
      { texto: "as desigualdades entre as regiões administrativas do DF na oferta de serviços e programas.", correta: true },
      { texto: "apenas o Plano Piloto.", correta: false },
      { texto: "somente as áreas rurais.", correta: false },
      { texto: "a oferta idêntica em todos os territórios, sem diferenciação.", correta: false },
      { texto: "a exclusão das regiões mais vulneráveis.", correta: false },
    ],
    explicacao:
      "A territorialização leva em conta as desigualdades entre as regiões administrativas do DF, priorizando as áreas de maior vulnerabilidade na oferta de serviços e programas.",
    fonteLegal: "Plano DF Social; PNAS/2004",
    palavrasChave: ["territorialização", "regiões administrativas"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A sustentabilidade dos resultados do Plano DF Social depende, sobretudo, de:",
    alternativas: [
      { texto: "combinar proteção social com inclusão produtiva e acesso a direitos, evitando a dependência permanente de benefícios.", correta: true },
      { texto: "manter as famílias indefinidamente fora do mercado de trabalho.", correta: false },
      { texto: "reduzir a oferta de serviços públicos.", correta: false },
      { texto: "ampliar a desigualdade regional.", correta: false },
      { texto: "concentrar os recursos nas famílias de maior renda.", correta: false },
    ],
    explicacao:
      "Resultados sustentáveis exigem articular a proteção social imediata com estratégias de inclusão produtiva e acesso a direitos, promovendo a autonomia das famílias a médio e longo prazo.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["sustentabilidade", "inclusão produtiva", "autonomia"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A relação do Plano DF Social com os benefícios eventuais evidencia que estes:",
    alternativas: [
      { texto: "atendem situações temporárias (como nascimento, morte e calamidade) dentro da rede de proteção.", correta: true },
      { texto: "são benefícios permanentes equivalentes a um salário mínimo.", correta: false },
      { texto: "substituem os serviços socioassistenciais.", correta: false },
      { texto: "são pagos apenas a servidores.", correta: false },
      { texto: "constituem aposentadoria.", correta: false },
    ],
    explicacao:
      "Os benefícios eventuais (provisões suplementares e provisórias) integram a rede de proteção articulada pelo plano, atendendo situações temporárias como nascimento, morte, vulnerabilidade temporária e calamidade.",
    fonteLegal: "Plano DF Social; LOAS, art. 22",
    palavrasChave: ["benefícios eventuais", "provisório"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A perspectiva de direitos no Plano DF Social significa que a proteção social é entendida como:",
    alternativas: [
      { texto: "um direito do cidadão e dever do Estado, e não como favor ou caridade.", correta: true },
      { texto: "uma concessão facultativa do gestor.", correta: false },
      { texto: "um benefício condicionado a contribuição.", correta: false },
      { texto: "uma prática meramente filantrópica.", correta: false },
      { texto: "um serviço exclusivamente privado.", correta: false },
    ],
    explicacao:
      "Alinhado à CF/1988 e à LOAS, o plano trata a proteção social como direito do cidadão e dever do Estado, superando a lógica do assistencialismo e da caridade.",
    fonteLegal: "Plano DF Social; CF/1988, art. 203",
    palavrasChave: ["direito", "dever do Estado"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A articulação do Plano DF Social com a política de habitação e moradia é relevante porque:",
    alternativas: [
      { texto: "a moradia digna é determinante para a superação da pobreza e a proteção das famílias.", correta: true },
      { texto: "a habitação não tem relação com a proteção social.", correta: false },
      { texto: "a moradia deve ser negada às famílias vulneráveis.", correta: false },
      { texto: "a política social ignora as condições de habitação.", correta: false },
      { texto: "a habitação é tema apenas tributário.", correta: false },
    ],
    explicacao:
      "A moradia digna é um determinante social: a articulação com políticas de habitação fortalece a superação da pobreza e a proteção integral das famílias, na lógica intersetorial do plano.",
    fonteLegal: "Plano DF Social (GDF/SEDES)",
    palavrasChave: ["habitação", "moradia", "intersetorialidade"],
  },
];

export default questoes;
