import type { QSeed } from "./tipos";

const A = "PNAS";

const questoes: QSeed[] = [
  {
    assunto: A,
    subassunto: "Princípios",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Constitui princípio democrático da PNAS:",
    alternativas: [
      { texto: "supremacia do atendimento às necessidades sociais sobre as exigências de rentabilidade econômica.", correta: true },
      { texto: "vinculação do acesso à capacidade de contribuição.", correta: false },
      { texto: "centralização das ações na esfera federal.", correta: false },
      { texto: "restrição dos direitos a grupos específicos.", correta: false },
      { texto: "primazia do lucro sobre o interesse público.", correta: false },
    ],
    explicacao:
      "A PNAS incorpora os princípios da LOAS (art. 4º), entre eles a supremacia do atendimento às necessidades sociais sobre as exigências de rentabilidade econômica.",
    fonteLegal: "PNAS/2004; LOAS, art. 4º",
    palavrasChave: ["princípios", "necessidades sociais"],
  },
  {
    assunto: A,
    subassunto: "Princípios",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A universalização dos direitos sociais, como princípio da PNAS, significa:",
    alternativas: [
      { texto: "tornar o destinatário da assistência alcançável pelas demais políticas públicas.", correta: true },
      { texto: "atender apenas quem comprovar contribuição prévia.", correta: false },
      { texto: "limitar o atendimento a uma única política setorial.", correta: false },
      { texto: "excluir do acesso quem está em extrema pobreza.", correta: false },
      { texto: "privatizar a oferta dos serviços.", correta: false },
    ],
    explicacao:
      "A universalização dos direitos sociais visa tornar o usuário da assistência social alcançável também pelas demais políticas públicas, ampliando a proteção social de forma integrada.",
    fonteLegal: "PNAS/2004; LOAS, art. 4º",
    palavrasChave: ["universalização", "direitos sociais"],
  },
  {
    assunto: A,
    subassunto: "Objetivos",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Entre os objetivos da PNAS está:",
    alternativas: [
      { texto: "prover serviços, programas, projetos e benefícios de proteção social básica e especial.", correta: true },
      { texto: "conceder aposentadorias por idade.", correta: false },
      { texto: "fiscalizar tributos municipais.", correta: false },
      { texto: "organizar o sistema prisional.", correta: false },
      { texto: "regular o mercado financeiro.", correta: false },
    ],
    explicacao:
      "A PNAS tem como objetivos prover serviços, programas, projetos e benefícios de proteção social básica e/ou especial para famílias, indivíduos e grupos que deles necessitarem.",
    fonteLegal: "PNAS/2004",
    palavrasChave: ["objetivos", "proteção básica", "proteção especial"],
  },
  {
    assunto: A,
    subassunto: "Matricialidade sociofamiliar",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A matricialidade sociofamiliar, na PNAS, expressa-se pelo fato de que:",
    alternativas: [
      { texto: "a família é o núcleo central das ações de proteção social.", correta: true },
      { texto: "o indivíduo é atendido sempre de forma isolada do contexto familiar.", correta: false },
      { texto: "apenas famílias com renda formal podem ser atendidas.", correta: false },
      { texto: "a escola substitui a família na proteção social.", correta: false },
      { texto: "o Estado assume a guarda de todos os usuários.", correta: false },
    ],
    explicacao:
      "A matricialidade sociofamiliar coloca a família no centro das ações da política, reconhecendo-a como espaço privilegiado de proteção e socialização, considerados seus vínculos e seu território.",
    fonteLegal: "PNAS/2004",
    palavrasChave: ["matricialidade", "família"],
  },
  {
    assunto: A,
    subassunto: "Territorialização",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O princípio organizativo da territorialização implica:",
    alternativas: [
      { texto: "organizar a oferta dos serviços a partir do território e de suas vulnerabilidades.", correta: true },
      { texto: "atender somente a população do centro das cidades.", correta: false },
      { texto: "ignorar as características locais de risco social.", correta: false },
      { texto: "concentrar todos os serviços em uma única unidade nacional.", correta: false },
      { texto: "vedar a instalação de CRAS em áreas vulneráveis.", correta: false },
    ],
    explicacao:
      "A territorialização orienta a localização dos equipamentos (como o CRAS) e a oferta de serviços conforme as vulnerabilidades e os riscos presentes no território, aproximando a proteção da população.",
    fonteLegal: "PNAS/2004; NOB-SUAS",
    palavrasChave: ["território", "vulnerabilidade"],
  },
  {
    assunto: A,
    subassunto: "Proteção Social Básica (PSB)",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A Proteção Social Básica tem caráter:",
    alternativas: [
      { texto: "preventivo, voltado a fortalecer vínculos e evitar situações de risco.", correta: true },
      { texto: "exclusivamente curativo, após o rompimento de vínculos.", correta: false },
      { texto: "punitivo em relação às famílias.", correta: false },
      { texto: "hospitalar e ambulatorial.", correta: false },
      { texto: "estritamente previdenciário.", correta: false },
    ],
    explicacao:
      "A PSB tem caráter preventivo e visa fortalecer vínculos familiares e comunitários, prevenindo situações de risco por meio de serviços como o PAIF e o SCFV, ofertados no CRAS.",
    fonteLegal: "PNAS/2004",
    palavrasChave: ["PSB", "prevenção", "vínculos"],
  },
  {
    assunto: A,
    subassunto: "Proteção Social Básica (PSB)",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "São serviços típicos da Proteção Social Básica:",
    alternativas: [
      { texto: "PAIF e Serviço de Convivência e Fortalecimento de Vínculos (SCFV).", correta: true },
      { texto: "PAEFI e Serviço de Acolhimento Institucional.", correta: false },
      { texto: "Serviço de abordagem social e medidas socioeducativas em meio aberto.", correta: false },
      { texto: "Serviço de proteção em situações de calamidade de alta complexidade.", correta: false },
      { texto: "Atendimento hospitalar de urgência.", correta: false },
    ],
    explicacao:
      "São serviços da PSB o PAIF (Serviço de Proteção e Atendimento Integral à Família), o SCFV e o Serviço de Proteção Social Básica no Domicílio para PcD e idosas.",
    fonteLegal: "Tipificação Nacional de Serviços Socioassistenciais",
    palavrasChave: ["PAIF", "SCFV", "PSB"],
  },
  {
    assunto: A,
    subassunto: "Proteção Social Especial (PSE)",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A Proteção Social Especial de média complexidade atende:",
    alternativas: [
      { texto: "famílias e indivíduos com direitos violados, mas cujos vínculos familiares não foram rompidos.", correta: true },
      { texto: "apenas famílias sem qualquer violação de direitos.", correta: false },
      { texto: "exclusivamente pessoas com vínculos totalmente rompidos.", correta: false },
      { texto: "somente a população que nunca acessou serviços.", correta: false },
      { texto: "unicamente pessoas em situação de rua acolhidas.", correta: false },
    ],
    explicacao:
      "A PSE de média complexidade atende situações de violação de direitos em que os vínculos familiares e comunitários não foram rompidos, sendo o PAEFI, ofertado no CREAS, seu serviço de referência.",
    fonteLegal: "PNAS/2004; Tipificação Nacional",
    palavrasChave: ["PSE", "média complexidade", "PAEFI"],
  },
  {
    assunto: A,
    subassunto: "Proteção Social Especial (PSE)",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A Proteção Social Especial de alta complexidade caracteriza-se por:",
    alternativas: [
      { texto: "ofertar acolhimento a quem está com vínculos rompidos ou ameaçados, fora do núcleo familiar.", correta: true },
      { texto: "prestar apenas orientação jurídica preventiva.", correta: false },
      { texto: "substituir a Proteção Social Básica.", correta: false },
      { texto: "atender exclusivamente por telefone.", correta: false },
      { texto: "conceder somente benefícios financeiros.", correta: false },
    ],
    explicacao:
      "A alta complexidade oferta serviços de acolhimento (institucional ou em família acolhedora) e proteção integral a indivíduos e famílias com vínculos rompidos ou ameaçados, garantindo moradia, alimentação e proteção.",
    fonteLegal: "PNAS/2004; Tipificação Nacional",
    palavrasChave: ["alta complexidade", "acolhimento"],
  },
  {
    assunto: A,
    subassunto: "Proteção Social Básica (PSB)",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O equipamento público de referência da Proteção Social Básica é o:",
    alternativas: [
      { texto: "CRAS.", correta: true },
      { texto: "CREAS.", correta: false },
      { texto: "Centro POP.", correta: false },
      { texto: "Hospital de referência.", correta: false },
      { texto: "Conselho Tutelar.", correta: false },
    ],
    explicacao:
      "O CRAS (Centro de Referência de Assistência Social) é a unidade pública estatal da PSB, porta de entrada do SUAS no território.",
    fonteLegal: "PNAS/2004; NOB-SUAS",
    palavrasChave: ["CRAS", "PSB", "porta de entrada"],
  },
  {
    assunto: A,
    subassunto: "Proteção Social Especial (PSE)",
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "O Centro POP é uma unidade voltada, prioritariamente, ao atendimento de:",
    alternativas: [
      { texto: "pessoas em situação de rua.", correta: true },
      { texto: "crianças em acolhimento institucional.", correta: false },
      { texto: "idosos em instituições de longa permanência.", correta: false },
      { texto: "famílias sem qualquer vulnerabilidade.", correta: false },
      { texto: "trabalhadores formais em férias.", correta: false },
    ],
    explicacao:
      "O Centro de Referência Especializado para População em Situação de Rua (Centro POP) é unidade da PSE que oferta o Serviço Especializado para Pessoas em Situação de Rua.",
    fonteLegal: "Tipificação Nacional; SUAS",
    palavrasChave: ["Centro POP", "situação de rua"],
  },
  {
    assunto: A,
    subassunto: "Objetivos",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A PNAS adota como base territorial e de planejamento a lógica de:",
    alternativas: [
      { texto: "porte dos municípios e regionalização, considerando densidade populacional e vulnerabilidades.", correta: true },
      { texto: "distribuição de recursos por sorteio.", correta: false },
      { texto: "atendimento idêntico em todos os territórios, sem diferenciação.", correta: false },
      { texto: "exclusão dos pequenos municípios da rede.", correta: false },
      { texto: "concentração de serviços apenas nas capitais.", correta: false },
    ],
    explicacao:
      "A PNAS organiza a oferta considerando o porte dos municípios (pequeno, médio, grande, metrópole) e a regionalização, adequando os serviços às características e vulnerabilidades de cada território.",
    fonteLegal: "PNAS/2004",
    palavrasChave: ["porte", "regionalização", "território"],
  },
  {
    assunto: A,
    subassunto: "Princípios",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O respeito à dignidade do cidadão e à sua autonomia, na PNAS, implica:",
    alternativas: [
      { texto: "vedar qualquer comprovação vexatória de necessidade para acesso aos serviços.", correta: true },
      { texto: "exigir exposição pública da situação de pobreza.", correta: false },
      { texto: "condicionar o atendimento à filiação partidária.", correta: false },
      { texto: "permitir tratamento discriminatório por território.", correta: false },
      { texto: "restringir o direito à informação.", correta: false },
    ],
    explicacao:
      "Entre os princípios está o respeito à dignidade do cidadão, à sua autonomia e ao direito a benefícios e serviços de qualidade, vedando-se qualquer comprovação vexatória da necessidade.",
    fonteLegal: "LOAS, art. 4º, III; PNAS/2004",
    palavrasChave: ["dignidade", "autonomia", "não vexatório"],
  },
  {
    assunto: A,
    subassunto: "Matricialidade sociofamiliar",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A concepção de família adotada pela PNAS é:",
    alternativas: [
      { texto: "ampla, reconhecendo diferentes arranjos e configurações familiares.", correta: true },
      { texto: "restrita ao modelo nuclear tradicional.", correta: false },
      { texto: "limitada a famílias com casamento civil.", correta: false },
      { texto: "exclusiva de famílias com filhos.", correta: false },
      { texto: "vinculada à existência de renda formal.", correta: false },
    ],
    explicacao:
      "A PNAS adota concepção ampliada de família, reconhecendo a diversidade de arranjos e configurações, e não apenas o modelo nuclear tradicional.",
    fonteLegal: "PNAS/2004",
    palavrasChave: ["família", "arranjos", "diversidade"],
  },
  {
    assunto: A,
    subassunto: "Objetivos",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Os usuários da política de assistência social, segundo a PNAS, são:",
    alternativas: [
      { texto: "cidadãos e grupos em situação de vulnerabilidade e risco social.", correta: true },
      { texto: "apenas pessoas com deficiência.", correta: false },
      { texto: "exclusivamente idosos.", correta: false },
      { texto: "somente trabalhadores sindicalizados.", correta: false },
      { texto: "apenas crianças e adolescentes.", correta: false },
    ],
    explicacao:
      "A PNAS define como usuários cidadãos e grupos em situação de vulnerabilidade e risco social, incluindo famílias com perda ou fragilidade de vínculos, ciclos de vida, exclusão pela pobreza, entre outros.",
    fonteLegal: "PNAS/2004",
    palavrasChave: ["usuários", "vulnerabilidade", "risco"],
  },
  {
    assunto: A,
    subassunto: "Territorialização",
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A vigilância socioassistencial, articulada à territorialização, tem por finalidade:",
    alternativas: [
      { texto: "conhecer a presença das vulnerabilidades e a oferta de serviços no território para subsidiar a gestão.", correta: true },
      { texto: "fiscalizar e multar famílias inadimplentes.", correta: false },
      { texto: "substituir o trabalho dos CRAS.", correta: false },
      { texto: "definir a política tributária municipal.", correta: false },
      { texto: "controlar o orçamento da saúde.", correta: false },
    ],
    explicacao:
      "A vigilância socioassistencial produz informações territorializadas sobre vulnerabilidades, riscos e a oferta de serviços, apoiando o planejamento e a gestão da proteção social.",
    fonteLegal: "PNAS/2004; NOB-SUAS; LOAS, art. 6º-A",
    palavrasChave: ["vigilância", "território", "gestão"],
  },
  {
    assunto: A,
    subassunto: "Proteção Social Básica (PSB)",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O Serviço de Convivência e Fortalecimento de Vínculos (SCFV) destina-se a:",
    alternativas: [
      { texto: "complementar o trabalho social com famílias, prevenindo riscos por meio de atividades em grupo.", correta: true },
      { texto: "acolher pessoas com vínculos rompidos em abrigos.", correta: false },
      { texto: "prestar atendimento médico especializado.", correta: false },
      { texto: "aplicar medidas socioeducativas privativas de liberdade.", correta: false },
      { texto: "conceder benefícios previdenciários.", correta: false },
    ],
    explicacao:
      "O SCFV é serviço da PSB, organizado em grupos por ciclos de vida, que complementa o PAIF e atua na prevenção de situações de risco, fortalecendo vínculos familiares e comunitários.",
    fonteLegal: "Tipificação Nacional de Serviços Socioassistenciais",
    palavrasChave: ["SCFV", "convivência", "vínculos"],
  },
  {
    assunto: A,
    subassunto: "Proteção Social Especial (PSE)",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O serviço de referência da Proteção Social Especial de média complexidade, ofertado no CREAS, é o:",
    alternativas: [
      { texto: "PAEFI.", correta: true },
      { texto: "PAIF.", correta: false },
      { texto: "SCFV.", correta: false },
      { texto: "BPC.", correta: false },
      { texto: "Bolsa Família.", correta: false },
    ],
    explicacao:
      "O PAEFI (Serviço de Proteção e Atendimento Especializado a Famílias e Indivíduos) é o serviço de referência da média complexidade, ofertado no CREAS, para situações de violação de direitos.",
    fonteLegal: "Tipificação Nacional; PNAS/2004",
    palavrasChave: ["PAEFI", "CREAS", "média complexidade"],
  },
  {
    assunto: A,
    subassunto: "Princípios",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A igualdade de direitos no acesso ao atendimento, sem discriminação, é, na PNAS, um:",
    alternativas: [
      { texto: "princípio que veda qualquer forma de discriminação no acesso.", correta: true },
      { texto: "critério de exclusão por território.", correta: false },
      { texto: "requisito de contribuição financeira.", correta: false },
      { texto: "fator de seleção por renda apenas.", correta: false },
      { texto: "elemento facultativo da política.", correta: false },
    ],
    explicacao:
      "A igualdade de direitos no acesso ao atendimento, sem discriminação de qualquer natureza, é princípio da assistência social, garantindo a equidade.",
    fonteLegal: "LOAS, art. 4º, IV; PNAS/2004",
    palavrasChave: ["igualdade", "não discriminação"],
  },
  {
    assunto: A,
    subassunto: "Objetivos",
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A intersetorialidade, na implementação da PNAS, é entendida como:",
    alternativas: [
      { texto: "articulação entre políticas públicas para a proteção integral dos usuários.", correta: true },
      { texto: "atuação isolada da assistência social.", correta: false },
      { texto: "transferência da política à iniciativa privada.", correta: false },
      { texto: "sobreposição de competências entre conselhos.", correta: false },
      { texto: "eliminação do controle social.", correta: false },
    ],
    explicacao:
      "A intersetorialidade pressupõe a articulação da assistência com saúde, educação, trabalho, habitação e outras políticas, buscando respostas integrais às múltiplas vulnerabilidades das famílias.",
    fonteLegal: "PNAS/2004",
    palavrasChave: ["intersetorialidade", "articulação"],
  },
  {
    assunto: A,
    subassunto: "Matricialidade sociofamiliar",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O trabalho social com famílias, eixo da matricialidade, tem como foco:",
    alternativas: [
      { texto: "fortalecer a função protetiva da família e prevenir a ruptura de vínculos.", correta: true },
      { texto: "responsabilizar exclusivamente a família por suas vulnerabilidades.", correta: false },
      { texto: "afastar definitivamente os filhos do convívio familiar.", correta: false },
      { texto: "substituir as políticas universais.", correta: false },
      { texto: "priorizar a punição em vez do cuidado.", correta: false },
    ],
    explicacao:
      "O trabalho social com famílias visa fortalecer a função protetiva da família, prevenir a ruptura de vínculos, promover acesso a direitos e melhorar a qualidade de vida, sem culpabilizar as famílias por suas condições.",
    fonteLegal: "PNAS/2004; Tipificação Nacional (PAIF)",
    palavrasChave: ["trabalho com famílias", "função protetiva"],
  },
  {
    assunto: A,
    subassunto: "Proteção Social Básica (PSB)",
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A busca ativa, no contexto da PSB, refere-se a:",
    alternativas: [
      { texto: "identificar ativamente famílias e indivíduos em vulnerabilidade no território.", correta: true },
      { texto: "aguardar passivamente a procura espontânea dos usuários.", correta: false },
      { texto: "cobrar contribuições das famílias atendidas.", correta: false },
      { texto: "encaminhar todos os usuários ao Judiciário.", correta: false },
      { texto: "restringir o atendimento a quem já é cadastrado.", correta: false },
    ],
    explicacao:
      "A busca ativa é estratégia da PSB para localizar e incluir famílias e indivíduos em situação de vulnerabilidade que não acessam espontaneamente os serviços, ampliando a cobertura da proteção.",
    fonteLegal: "PNAS/2004; NOB-SUAS",
    palavrasChave: ["busca ativa", "cobertura", "território"],
  },
  {
    assunto: A,
    subassunto: "Proteção Social Especial (PSE)",
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "São exemplos de serviços de acolhimento (alta complexidade):",
    alternativas: [
      { texto: "abrigo institucional, casa-lar, casa de passagem e família acolhedora.", correta: true },
      { texto: "PAIF e SCFV.", correta: false },
      { texto: "atendimento ambulatorial e internação hospitalar.", correta: false },
      { texto: "ensino fundamental e médio.", correta: false },
      { texto: "perícia médica do INSS.", correta: false },
    ],
    explicacao:
      "Entre os serviços de acolhimento da alta complexidade estão abrigo institucional, casa-lar, casa de passagem, residência inclusiva e serviço em família acolhedora.",
    fonteLegal: "Tipificação Nacional de Serviços Socioassistenciais",
    palavrasChave: ["acolhimento", "abrigo", "família acolhedora"],
  },
];

export default questoes;
