import type { QSeed } from "./tipos";

const A = "Restaurante Comunitario";

const questoes: QSeed[] = [
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Os Restaurantes Comunitários, no Distrito Federal, têm por finalidade:",
    alternativas: [
      { texto: "ofertar refeições saudáveis a preço acessível, promovendo a segurança alimentar e nutricional.", correta: true },
      { texto: "comercializar refeições de alto padrão a preço de mercado.", correta: false },
      { texto: "distribuir gás de cozinha às famílias.", correta: false },
      { texto: "vender medicamentos subsidiados.", correta: false },
      { texto: "oferecer transporte gratuito.", correta: false },
    ],
    explicacao:
      "Os Restaurantes Comunitários ofertam refeições nutricionalmente adequadas a preço acessível (subsidiado), atuando na promoção da segurança alimentar e nutricional da população em vulnerabilidade.",
    fonteLegal: "Programa de Restaurantes Comunitários (GDF/SEDES)",
    palavrasChave: ["refeições", "preço acessível", "SAN"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O público atendido pelos Restaurantes Comunitários é, prioritariamente:",
    alternativas: [
      { texto: "a população em situação de vulnerabilidade social e insegurança alimentar.", correta: true },
      { texto: "exclusivamente turistas.", correta: false },
      { texto: "apenas servidores públicos.", correta: false },
      { texto: "somente famílias de alta renda.", correta: false },
      { texto: "apenas grandes empresas.", correta: false },
    ],
    explicacao:
      "Embora abertos ao público, os Restaurantes Comunitários priorizam o atendimento à população em situação de vulnerabilidade social e insegurança alimentar.",
    fonteLegal: "Programa de Restaurantes Comunitários (GDF/SEDES)",
    palavrasChave: ["vulnerabilidade", "insegurança alimentar"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O caráter subsidiado do preço das refeições nos Restaurantes Comunitários significa que:",
    alternativas: [
      { texto: "parte do custo é coberta pelo poder público, reduzindo o valor pago pelo usuário.", correta: true },
      { texto: "o usuário paga o custo integral da refeição.", correta: false },
      { texto: "as refeições têm preço de mercado.", correta: false },
      { texto: "o serviço é financiado exclusivamente por empresas privadas.", correta: false },
      { texto: "o preço é definido pelo próprio usuário.", correta: false },
    ],
    explicacao:
      "O preço é subsidiado: o poder público cobre parte significativa do custo, de modo que o usuário paga um valor reduzido pela refeição, viabilizando o acesso à alimentação.",
    fonteLegal: "Programa de Restaurantes Comunitários (GDF/SEDES)",
    palavrasChave: ["subsídio", "preço reduzido"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Os Restaurantes Comunitários integram a política de:",
    alternativas: [
      { texto: "segurança alimentar e nutricional do DF.", correta: true },
      { texto: "regulação do trânsito.", correta: false },
      { texto: "arrecadação tributária.", correta: false },
      { texto: "gestão de pessoal.", correta: false },
      { texto: "planejamento urbano.", correta: false },
    ],
    explicacao:
      "Os Restaurantes Comunitários compõem a política de segurança alimentar e nutricional do DF, articulada à rede de proteção social e gerida pela SEDES.",
    fonteLegal: "Programa de Restaurantes Comunitários; LOSAN",
    palavrasChave: ["SAN", "proteção social"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A oferta de refeições por equipamentos públicos de alimentação e nutrição (como os Restaurantes Comunitários) é, no campo da SAN, classificada como:",
    alternativas: [
      { texto: "equipamento público de segurança alimentar e nutricional.", correta: true },
      { texto: "benefício previdenciário.", correta: false },
      { texto: "serviço de saúde de alta complexidade.", correta: false },
      { texto: "programa de habitação.", correta: false },
      { texto: "ação de defesa do consumidor.", correta: false },
    ],
    explicacao:
      "Os Restaurantes Comunitários são equipamentos públicos de SAN, ao lado de outras estruturas como cozinhas comunitárias e bancos de alimentos, voltadas a ampliar o acesso à alimentação adequada.",
    fonteLegal: "Programa de Restaurantes Comunitários; LOSAN",
    palavrasChave: ["equipamento público", "SAN"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O órgão gestor dos Restaurantes Comunitários no DF é:",
    alternativas: [
      { texto: "a Secretaria de Desenvolvimento Social (SEDES).", correta: true },
      { texto: "a Secretaria de Fazenda.", correta: false },
      { texto: "a Secretaria de Transportes.", correta: false },
      { texto: "o Tribunal de Contas.", correta: false },
      { texto: "a Defensoria Pública.", correta: false },
    ],
    explicacao:
      "A gestão dos Restaurantes Comunitários cabe à SEDES, responsável pela política de desenvolvimento e assistência social do DF, incluindo a segurança alimentar.",
    fonteLegal: "Programa de Restaurantes Comunitários (GDF/SEDES)",
    palavrasChave: ["SEDES", "gestão"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A localização dos Restaurantes Comunitários costuma priorizar:",
    alternativas: [
      { texto: "regiões administrativas de maior vulnerabilidade social e grande circulação de pessoas.", correta: true },
      { texto: "áreas de alta renda.", correta: false },
      { texto: "locais isolados e de difícil acesso.", correta: false },
      { texto: "regiões sem qualquer demanda.", correta: false },
      { texto: "exclusivamente o Plano Piloto.", correta: false },
    ],
    explicacao:
      "A instalação prioriza territórios de maior vulnerabilidade social e grande circulação (terminais, centros urbanos), de modo a alcançar quem mais necessita do serviço.",
    fonteLegal: "Programa de Restaurantes Comunitários (GDF/SEDES)",
    palavrasChave: ["localização", "vulnerabilidade", "território"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A qualidade nutricional das refeições servidas nos Restaurantes Comunitários é importante porque:",
    alternativas: [
      { texto: "a segurança alimentar e nutricional pressupõe alimentação adequada e saudável, não apenas calorias.", correta: true },
      { texto: "o objetivo é apenas reduzir custos, sem preocupação nutricional.", correta: false },
      { texto: "a nutrição não tem relação com a SAN.", correta: false },
      { texto: "as refeições devem ser de baixo valor nutritivo.", correta: false },
      { texto: "a qualidade é irrelevante para o programa.", correta: false },
    ],
    explicacao:
      "A SAN abrange o acesso a alimentos de qualidade; por isso, as refeições devem ser nutricionalmente adequadas e saudáveis, e não apenas baratas, respeitando hábitos alimentares.",
    fonteLegal: "Programa de Restaurantes Comunitários; LOSAN",
    palavrasChave: ["qualidade nutricional", "alimentação saudável"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O acesso ao Restaurante Comunitário caracteriza-se por ser:",
    alternativas: [
      { texto: "aberto ao público, mediante pagamento de valor simbólico/subsidiado.", correta: true },
      { texto: "restrito a quem comprova contribuição previdenciária.", correta: false },
      { texto: "exclusivo de famílias cadastradas em outro programa.", correta: false },
      { texto: "gratuito apenas para empresários.", correta: false },
      { texto: "vedado à população em situação de rua.", correta: false },
    ],
    explicacao:
      "Em regra, o serviço é aberto ao público mediante pagamento de valor simbólico/subsidiado, com atenção prioritária à população vulnerável, incluindo pessoas em situação de rua.",
    fonteLegal: "Programa de Restaurantes Comunitários (GDF/SEDES)",
    palavrasChave: ["acesso", "valor simbólico"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A relação dos Restaurantes Comunitários com a população em situação de rua é relevante porque:",
    alternativas: [
      { texto: "garantem acesso à alimentação a um público com elevada insegurança alimentar.", correta: true },
      { texto: "proíbem o atendimento dessa população.", correta: false },
      { texto: "substituem os serviços de acolhimento.", correta: false },
      { texto: "não têm qualquer relação com esse público.", correta: false },
      { texto: "destinam-se apenas a turistas.", correta: false },
    ],
    explicacao:
      "Os Restaurantes Comunitários são importantes para a população em situação de rua, que enfrenta alta insegurança alimentar, articulando-se com serviços como o Centro POP.",
    fonteLegal: "Programa de Restaurantes Comunitários; SUAS",
    palavrasChave: ["população de rua", "Centro POP"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A articulação dos Restaurantes Comunitários com a agricultura familiar pode:",
    alternativas: [
      { texto: "fortalecer a economia local e a oferta de alimentos saudáveis por meio de compras públicas.", correta: true },
      { texto: "encarecer as refeições e excluir produtores locais.", correta: false },
      { texto: "vedar a compra de alimentos da agricultura familiar.", correta: false },
      { texto: "substituir a SAN pela política industrial.", correta: false },
      { texto: "eliminar a fiscalização sanitária.", correta: false },
    ],
    explicacao:
      "A aquisição de alimentos da agricultura familiar (compras públicas) fortalece a economia local, gera renda no campo e amplia a oferta de alimentos saudáveis nos equipamentos de SAN.",
    fonteLegal: "Programa de Restaurantes Comunitários; políticas de SAN",
    palavrasChave: ["agricultura familiar", "compras públicas"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Os Restaurantes Comunitários contribuem para o direito humano à:",
    alternativas: [
      { texto: "alimentação adequada.", correta: true },
      { texto: "propriedade privada.", correta: false },
      { texto: "livre concorrência.", correta: false },
      { texto: "anterioridade tributária.", correta: false },
      { texto: "autonomia universitária.", correta: false },
    ],
    explicacao:
      "O programa concretiza o direito humano à alimentação adequada (DHAA), reconhecido na CF/1988 (art. 6º) e na LOSAN.",
    fonteLegal: "CF/1988, art. 6º; LOSAN",
    palavrasChave: ["DHAA", "alimentação adequada"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O financiamento dos Restaurantes Comunitários ocorre, sobretudo, por:",
    alternativas: [
      { texto: "recursos públicos do DF, que subsidiam o custo das refeições.", correta: true },
      { texto: "contribuições previdenciárias dos usuários.", correta: false },
      { texto: "tarifas integrais pagas pelos usuários.", correta: false },
      { texto: "doações obrigatórias de empresas.", correta: false },
      { texto: "empréstimos contraídos pelos usuários.", correta: false },
    ],
    explicacao:
      "O serviço é mantido com recursos públicos do DF, que subsidiam o custo das refeições para mantê-las acessíveis à população vulnerável.",
    fonteLegal: "Programa de Restaurantes Comunitários; LOA do DF",
    palavrasChave: ["financiamento", "recursos públicos", "subsídio"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A oferta de mais de uma refeição (ex.: café, almoço e jantar) nos Restaurantes Comunitários visa:",
    alternativas: [
      { texto: "ampliar a cobertura da segurança alimentar ao longo do dia.", correta: true },
      { texto: "reduzir o acesso à alimentação.", correta: false },
      { texto: "encarecer o serviço propositalmente.", correta: false },
      { texto: "restringir o atendimento a um único horário.", correta: false },
      { texto: "substituir a transferência de renda.", correta: false },
    ],
    explicacao:
      "Ampliar os tipos de refeições ofertadas (café da manhã, almoço, jantar) aumenta a cobertura da SAN ao longo do dia, beneficiando especialmente quem está em maior vulnerabilidade.",
    fonteLegal: "Programa de Restaurantes Comunitários (GDF/SEDES)",
    palavrasChave: ["refeições", "cobertura", "SAN"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Os Restaurantes Comunitários são exemplo de ação:",
    alternativas: [
      { texto: "estatal de oferta direta de serviço de segurança alimentar.", correta: true },
      { texto: "exclusivamente privada e lucrativa.", correta: false },
      { texto: "de transferência de renda em dinheiro.", correta: false },
      { texto: "previdenciária.", correta: false },
      { texto: "de fiscalização tributária.", correta: false },
    ],
    explicacao:
      "Diferentemente da transferência de renda, os Restaurantes Comunitários representam a oferta direta de um serviço público de segurança alimentar (refeições prontas).",
    fonteLegal: "Programa de Restaurantes Comunitários (GDF/SEDES)",
    palavrasChave: ["oferta direta", "serviço público"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A higiene e a segurança sanitária na preparação das refeições nos Restaurantes Comunitários:",
    alternativas: [
      { texto: "devem observar normas sanitárias para garantir alimentos seguros à população.", correta: true },
      { texto: "são dispensáveis por se tratar de serviço subsidiado.", correta: false },
      { texto: "competem exclusivamente aos usuários.", correta: false },
      { texto: "não se aplicam a equipamentos públicos.", correta: false },
      { texto: "podem ser ignoradas em situações de demanda.", correta: false },
    ],
    explicacao:
      "Por ofertar alimentos à população, os Restaurantes Comunitários devem cumprir as normas de vigilância sanitária e de boas práticas, assegurando refeições seguras e de qualidade.",
    fonteLegal: "Programa de Restaurantes Comunitários; normas sanitárias",
    palavrasChave: ["vigilância sanitária", "boas práticas"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "Os Restaurantes Comunitários, ao reduzir o gasto das famílias com alimentação, produzem efeito de:",
    alternativas: [
      { texto: "aumento da renda disponível para outras necessidades essenciais.", correta: true },
      { texto: "redução do poder de compra das famílias.", correta: false },
      { texto: "elevação da insegurança alimentar.", correta: false },
      { texto: "concentração de renda.", correta: false },
      { texto: "aumento da carga tributária das famílias pobres.", correta: false },
    ],
    explicacao:
      "Ao baratear a alimentação, o serviço libera parte da renda familiar para outras necessidades essenciais (transporte, moradia, saúde), funcionando como uma renda indireta.",
    fonteLegal: "Programa de Restaurantes Comunitários (GDF/SEDES)",
    palavrasChave: ["renda disponível", "renda indireta"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A oferta dos Restaurantes Comunitários expressa o princípio da assistência social de:",
    alternativas: [
      { texto: "universalização do acesso e respeito à dignidade do usuário.", correta: true },
      { texto: "seletividade por capacidade contributiva.", correta: false },
      { texto: "primazia do lucro.", correta: false },
      { texto: "vedação ao acesso da população vulnerável.", correta: false },
      { texto: "exclusividade para servidores.", correta: false },
    ],
    explicacao:
      "O serviço materializa princípios como a universalização do acesso e o respeito à dignidade, oferecendo alimentação em ambiente que evita constrangimentos ao usuário.",
    fonteLegal: "LOAS, art. 4º; Programa de Restaurantes Comunitários",
    palavrasChave: ["universalização", "dignidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A articulação dos Restaurantes Comunitários com os CRAS pode permitir:",
    alternativas: [
      { texto: "identificar usuários em vulnerabilidade e encaminhá-los a outros serviços e benefícios.", correta: true },
      { texto: "impedir o acesso dos usuários à rede de proteção.", correta: false },
      { texto: "substituir os CRAS pelos restaurantes.", correta: false },
      { texto: "excluir os usuários da assistência social.", correta: false },
      { texto: "vedar o acompanhamento familiar.", correta: false },
    ],
    explicacao:
      "A articulação com os CRAS possibilita identificar usuários em vulnerabilidade que frequentam o restaurante e encaminhá-los a serviços e benefícios, ampliando a proteção social.",
    fonteLegal: "Programa de Restaurantes Comunitários; PNAS/2004",
    palavrasChave: ["CRAS", "encaminhamento", "rede"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O combate ao desperdício de alimentos, nos Restaurantes Comunitários, relaciona-se a:",
    alternativas: [
      { texto: "boas práticas de gestão e à promoção da sustentabilidade na SAN.", correta: true },
      { texto: "estímulo ao descarte de alimentos.", correta: false },
      { texto: "aumento do custo das refeições.", correta: false },
      { texto: "redução da qualidade nutricional.", correta: false },
      { texto: "vedação ao reaproveitamento adequado.", correta: false },
    ],
    explicacao:
      "A redução do desperdício é uma boa prática de gestão e contribui para a sustentabilidade e a eficiência dos equipamentos de SAN, sem prejuízo da qualidade e da segurança alimentar.",
    fonteLegal: "Programa de Restaurantes Comunitários; SAN",
    palavrasChave: ["desperdício", "sustentabilidade"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Os Restaurantes Comunitários e o Cartão Prato Cheio, no campo da SAN, são:",
    alternativas: [
      { texto: "ações complementares, uma de oferta direta de refeições e outra de transferência de renda para alimentos.", correta: true },
      { texto: "ações idênticas e redundantes.", correta: false },
      { texto: "benefícios previdenciários.", correta: false },
      { texto: "ações sem qualquer relação entre si.", correta: false },
      { texto: "programas de habitação.", correta: false },
    ],
    explicacao:
      "São ações complementares: o restaurante oferece refeições prontas subsidiadas e o Prato Cheio transfere renda para a compra de alimentos, ampliando o leque de respostas à insegurança alimentar.",
    fonteLegal: "Programas de SAN do DF (GDF/SEDES)",
    palavrasChave: ["complementaridade", "Prato Cheio"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A avaliação e o monitoramento dos Restaurantes Comunitários permitem:",
    alternativas: [
      { texto: "acompanhar a demanda, a qualidade do serviço e a cobertura territorial.", correta: true },
      { texto: "ocultar dados do serviço.", correta: false },
      { texto: "encerrar o controle social.", correta: false },
      { texto: "impedir melhorias no programa.", correta: false },
      { texto: "punir os usuários.", correta: false },
    ],
    explicacao:
      "O monitoramento e a avaliação acompanham indicadores como demanda atendida, qualidade das refeições e cobertura, subsidiando melhorias e a expansão do serviço.",
    fonteLegal: "Programa de Restaurantes Comunitários (GDF/SEDES)",
    palavrasChave: ["monitoramento", "avaliação", "cobertura"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "Como equipamento público de SAN, o Restaurante Comunitário difere de um benefício eventual porque:",
    alternativas: [
      { texto: "é um serviço continuado de oferta de refeições, e não uma provisão pontual para contingências.", correta: true },
      { texto: "ambos são provisões pontuais idênticas.", correta: false },
      { texto: "o restaurante é benefício previdenciário.", correta: false },
      { texto: "o benefício eventual oferta refeições prontas.", correta: false },
      { texto: "não há diferença entre eles.", correta: false },
    ],
    explicacao:
      "O Restaurante Comunitário é um serviço público continuado de SAN; o benefício eventual é uma provisão pontual (em pecúnia ou bens) para contingências específicas como nascimento, morte ou calamidade.",
    fonteLegal: "Programa de Restaurantes Comunitários; LOAS, art. 22",
    palavrasChave: ["serviço continuado", "benefício eventual", "diferença"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Um benefício social adicional dos Restaurantes Comunitários é:",
    alternativas: [
      { texto: "favorecer o convívio e a sociabilidade em espaço público de alimentação.", correta: true },
      { texto: "isolar os usuários.", correta: false },
      { texto: "estigmatizar quem utiliza o serviço.", correta: false },
      { texto: "reduzir o acesso à cidade.", correta: false },
      { texto: "restringir direitos sociais.", correta: false },
    ],
    explicacao:
      "Além da alimentação, o restaurante é um espaço de convívio e sociabilidade, contribuindo para o fortalecimento de vínculos comunitários e a dignidade no acesso à alimentação.",
    fonteLegal: "Programa de Restaurantes Comunitários (GDF/SEDES)",
    palavrasChave: ["convívio", "sociabilidade"],
  },
];

export default questoes;
