import type { QSeed } from "./tipos";

const A = "RIDE";

const questoes: QSeed[] = [
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A sigla RIDE, no contexto do Distrito Federal, significa:",
    alternativas: [
      { texto: "Região Integrada de Desenvolvimento do Distrito Federal e Entorno.", correta: true },
      { texto: "Rede Integrada de Defesa do Estado.", correta: false },
      { texto: "Regime Interno de Desenvolvimento Econômico.", correta: false },
      { texto: "Registro de Imóveis do Distrito e Entorno.", correta: false },
      { texto: "Repartição Interestadual de Despesas.", correta: false },
    ],
    explicacao:
      "RIDE é a Região Integrada de Desenvolvimento do Distrito Federal e Entorno, instituída para articular a ação administrativa da União, do DF e dos estados e municípios envolvidos.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["RIDE", "DF e Entorno"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A RIDE do DF e Entorno foi instituída pela:",
    alternativas: [
      { texto: "Lei Complementar nº 94/1998.", correta: true },
      { texto: "Lei nº 8.742/1993 (LOAS).", correta: false },
      { texto: "Lei nº 11.340/2006 (Maria da Penha).", correta: false },
      { texto: "Lei Complementar nº 840/2011.", correta: false },
      { texto: "Constituição de 1967.", correta: false },
    ],
    explicacao:
      "A RIDE do DF e Entorno foi criada pela Lei Complementar nº 94/1998 e regulamentada por decreto, com posteriores alterações que ampliaram os municípios integrantes.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["LC 94/1998", "instituição"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A RIDE do DF e Entorno é composta:",
    alternativas: [
      { texto: "pelo Distrito Federal e por municípios dos estados de Goiás e de Minas Gerais.", correta: true },
      { texto: "exclusivamente por municípios de Goiás.", correta: false },
      { texto: "apenas pelo Distrito Federal.", correta: false },
      { texto: "pelo DF e municípios de Goiás, Minas Gerais e Bahia.", correta: false },
      { texto: "por todos os municípios da região Centro-Oeste.", correta: false },
    ],
    explicacao:
      "A RIDE abrange o Distrito Federal e municípios dos estados de Goiás e de Minas Gerais, formando uma região para fins de articulação e desenvolvimento integrado.",
    fonteLegal: "Lei Complementar 94/1998 e alterações",
    palavrasChave: ["Goiás", "Minas Gerais", "composição"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O principal objetivo da criação da RIDE é:",
    alternativas: [
      { texto: "articular e harmonizar ações administrativas entre os entes para o desenvolvimento e a oferta de serviços públicos comuns.", correta: true },
      { texto: "criar um novo estado da federação.", correta: false },
      { texto: "extinguir os municípios do entorno.", correta: false },
      { texto: "transferir a capital federal.", correta: false },
      { texto: "unificar as polícias estaduais.", correta: false },
    ],
    explicacao:
      "A RIDE visa articular a ação administrativa da União, do DF, de Goiás, de Minas Gerais e dos municípios, para o desenvolvimento regional e a prestação de serviços públicos de interesse comum.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["articulação", "serviços comuns", "desenvolvimento"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "São exemplos de serviços públicos de interesse comum tratados no âmbito da RIDE:",
    alternativas: [
      { texto: "transporte, saneamento, saúde, educação e assistência social, entre outros.", correta: true },
      { texto: "apenas o serviço militar.", correta: false },
      { texto: "exclusivamente a emissão de moeda.", correta: false },
      { texto: "somente relações exteriores.", correta: false },
      { texto: "apenas a Justiça Eleitoral.", correta: false },
    ],
    explicacao:
      "A RIDE trata de serviços de interesse comum, como transporte, saneamento, uso de recursos hídricos, saúde, educação, assistência social e infraestrutura, que extrapolam os limites de um único ente.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["serviços comuns", "transporte", "saúde"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A natureza jurídica da RIDE pode ser descrita como:",
    alternativas: [
      { texto: "região para fins de articulação administrativa, sem constituir novo ente federativo.", correta: true },
      { texto: "novo ente federativo com autonomia política.", correta: false },
      { texto: "município único resultante da fusão de cidades.", correta: false },
      { texto: "autarquia federal com poder de legislar.", correta: false },
      { texto: "estado-membro da federação.", correta: false },
    ],
    explicacao:
      "A RIDE é um arranjo de articulação administrativa entre entes para o desenvolvimento integrado; não constitui novo ente federativo nem possui autonomia política própria.",
    fonteLegal: "Lei Complementar 94/1998; CF/1988",
    palavrasChave: ["natureza jurídica", "articulação"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A competência para instituir região integrada de desenvolvimento que envolva o DF e municípios de diferentes estados é:",
    alternativas: [
      { texto: "da União, mediante lei complementar.", correta: true },
      { texto: "exclusiva do Distrito Federal.", correta: false },
      { texto: "dos municípios do entorno, isoladamente.", correta: false },
      { texto: "do estado de Goiás, apenas.", correta: false },
      { texto: "de entidade privada.", correta: false },
    ],
    explicacao:
      "Por envolver entes de diferentes estados e o DF, a criação da RIDE é de competência da União, por meio de lei complementar, como ocorreu com a LC 94/1998.",
    fonteLegal: "CF/1988; Lei Complementar 94/1998",
    palavrasChave: ["competência da União", "lei complementar"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "O órgão colegiado responsável pela coordenação das atividades da RIDE é, historicamente:",
    alternativas: [
      { texto: "o Conselho Administrativo da Região Integrada de Desenvolvimento (COARIDE).", correta: true },
      { texto: "a Câmara Legislativa do DF.", correta: false },
      { texto: "o Tribunal de Contas da União.", correta: false },
      { texto: "o Conselho Nacional de Justiça.", correta: false },
      { texto: "a Assembleia de Goiás.", correta: false },
    ],
    explicacao:
      "A coordenação das ações da RIDE cabe ao Conselho Administrativo da RIDE (COARIDE), com representação dos entes envolvidos, voltado à articulação das políticas e dos investimentos.",
    fonteLegal: "Lei Complementar 94/1998 e regulamentação",
    palavrasChave: ["COARIDE", "coordenação"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A coordenação federal das políticas de desenvolvimento regional, incluindo a RIDE, cabe, em regra:",
    alternativas: [
      { texto: "ao órgão federal responsável pelo desenvolvimento regional (Ministério da Integração/Desenvolvimento Regional).", correta: true },
      { texto: "ao Ministério da Saúde, exclusivamente.", correta: false },
      { texto: "ao Banco Central.", correta: false },
      { texto: "ao Tribunal Superior Eleitoral.", correta: false },
      { texto: "a uma entidade privada.", correta: false },
    ],
    explicacao:
      "No plano federal, a política de desenvolvimento regional e a articulação das RIDEs cabem ao órgão responsável pela integração/desenvolvimento regional, atualmente o Ministério do Desenvolvimento Regional.",
    fonteLegal: "Legislação federal de desenvolvimento regional",
    palavrasChave: ["desenvolvimento regional", "coordenação federal"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A relação entre a RIDE e a política de assistência social está em que:",
    alternativas: [
      { texto: "a integração regional pode favorecer a oferta articulada de serviços socioassistenciais entre o DF e o entorno.", correta: true },
      { texto: "a assistência social é vedada na RIDE.", correta: false },
      { texto: "a RIDE substitui o SUAS.", correta: false },
      { texto: "a RIDE impede o atendimento de migrantes.", correta: false },
      { texto: "não há qualquer relação possível.", correta: false },
    ],
    explicacao:
      "A integração regional pode contribuir para articular serviços públicos comuns, inclusive de assistência social, considerando o intenso fluxo populacional entre o DF e os municípios do entorno.",
    fonteLegal: "Lei Complementar 94/1998; PNAS/2004",
    palavrasChave: ["assistência social", "serviços articulados"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "Um dos desafios sociais que justificam a articulação na RIDE é:",
    alternativas: [
      { texto: "o intenso deslocamento pendular de pessoas entre o entorno e o DF em busca de trabalho e serviços.", correta: true },
      { texto: "a ausência de população no entorno.", correta: false },
      { texto: "a inexistência de demanda por serviços públicos.", correta: false },
      { texto: "a total autossuficiência de cada município.", correta: false },
      { texto: "a proibição de circulação de pessoas.", correta: false },
    ],
    explicacao:
      "O deslocamento pendular diário de trabalhadores e usuários de serviços entre os municípios do entorno e o DF gera demandas comuns (transporte, saúde, assistência), o que justifica a articulação regional.",
    fonteLegal: "Contexto socioeconômico da RIDE",
    palavrasChave: ["deslocamento pendular", "demanda comum"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A RIDE busca enfrentar desigualdades regionais por meio de:",
    alternativas: [
      { texto: "planejamento e ações integradas de desenvolvimento entre os entes.", correta: true },
      { texto: "isolamento dos municípios do entorno.", correta: false },
      { texto: "concentração de todos os serviços no DF.", correta: false },
      { texto: "vedação a investimentos no entorno.", correta: false },
      { texto: "eliminação dos municípios.", correta: false },
    ],
    explicacao:
      "A RIDE tem por finalidade reduzir desigualdades regionais por meio do planejamento e de ações integradas de desenvolvimento, com investimentos coordenados entre os entes.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["desigualdades regionais", "planejamento integrado"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A diferença entre a RIDE e uma região metropolitana tradicional é que:",
    alternativas: [
      { texto: "a RIDE envolve entes de diferentes estados e o DF, sendo instituída por lei complementar federal, enquanto a região metropolitana, em regra, é criada por lei complementar estadual reunindo municípios de um mesmo estado.", correta: true },
      { texto: "não há qualquer diferença entre elas.", correta: false },
      { texto: "a região metropolitana abrange diferentes estados e a RIDE, apenas um município.", correta: false },
      { texto: "a RIDE é criada por lei municipal.", correta: false },
      { texto: "a região metropolitana é criada pela União.", correta: false },
    ],
    explicacao:
      "A RIDE, por reunir entes de estados distintos e o DF, é instituída por lei complementar federal; as regiões metropolitanas, em regra, são criadas por lei complementar estadual, agrupando municípios limítrofes de um mesmo estado.",
    fonteLegal: "CF/1988, art. 25, §3º; Lei Complementar 94/1998",
    palavrasChave: ["região metropolitana", "lei complementar", "diferença"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A integração de transporte público na RIDE é relevante porque:",
    alternativas: [
      { texto: "viabiliza o deslocamento da população entre o entorno e o DF para trabalho, estudo e serviços.", correta: true },
      { texto: "impede a circulação entre os municípios.", correta: false },
      { texto: "é vedada pela legislação.", correta: false },
      { texto: "não tem relação com o desenvolvimento regional.", correta: false },
      { texto: "destina-se apenas ao transporte de cargas.", correta: false },
    ],
    explicacao:
      "Dado o forte fluxo pendular, a integração do transporte público é um dos temas centrais da RIDE, viabilizando o acesso da população do entorno a trabalho, estudo e serviços no DF.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["transporte público", "integração"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Os municípios do entorno que integram a RIDE estão localizados, em sua maioria, no estado de:",
    alternativas: [
      { texto: "Goiás.", correta: true },
      { texto: "São Paulo.", correta: false },
      { texto: "Bahia.", correta: false },
      { texto: "Tocantins.", correta: false },
      { texto: "Mato Grosso.", correta: false },
    ],
    explicacao:
      "A maioria dos municípios do entorno integrantes da RIDE situa-se em Goiás (como Luziânia, Águas Lindas, Valparaíso, Formosa, entre outros), além de alguns municípios de Minas Gerais.",
    fonteLegal: "Lei Complementar 94/1998 e alterações",
    palavrasChave: ["Goiás", "entorno", "municípios"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A previsão de programas especiais e fundos para o desenvolvimento da RIDE tem por finalidade:",
    alternativas: [
      { texto: "financiar e viabilizar ações e investimentos de interesse comum da região.", correta: true },
      { texto: "concentrar recursos apenas no DF.", correta: false },
      { texto: "impedir investimentos no entorno.", correta: false },
      { texto: "substituir os orçamentos dos entes.", correta: false },
      { texto: "remunerar servidores do entorno.", correta: false },
    ],
    explicacao:
      "A legislação prevê instrumentos (programas e mecanismos de financiamento) para viabilizar investimentos e ações de interesse comum, fomentando o desenvolvimento integrado da região.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["financiamento", "investimentos", "fundo"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A articulação na RIDE pressupõe a participação:",
    alternativas: [
      { texto: "da União, do DF, dos estados de Goiás e de Minas Gerais e dos municípios envolvidos.", correta: true },
      { texto: "apenas da União.", correta: false },
      { texto: "exclusivamente dos municípios.", correta: false },
      { texto: "somente do DF.", correta: false },
      { texto: "de entidades privadas, com exclusão dos entes públicos.", correta: false },
    ],
    explicacao:
      "A gestão e a articulação da RIDE envolvem a União, o DF, os estados de Goiás e de Minas Gerais e os municípios integrantes, de forma cooperativa.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["participação", "cooperação federativa"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A inclusão de municípios na RIDE ao longo do tempo demonstra que:",
    alternativas: [
      { texto: "a composição da região pode ser alterada por norma específica, ampliando o número de municípios.", correta: true },
      { texto: "a composição é imutável desde 1998.", correta: false },
      { texto: "apenas o DF pode integrar a RIDE.", correta: false },
      { texto: "municípios não podem ser incluídos.", correta: false },
      { texto: "a RIDE foi extinta.", correta: false },
    ],
    explicacao:
      "A composição da RIDE foi ampliada ao longo do tempo por normas específicas, aumentando o número de municípios integrantes, conforme as necessidades de integração regional.",
    fonteLegal: "Lei Complementar 94/1998 e alterações posteriores",
    palavrasChave: ["composição", "ampliação", "municípios"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "A RIDE é um instrumento de:",
    alternativas: [
      { texto: "política de desenvolvimento regional e integração de serviços públicos.", correta: true },
      { texto: "política tributária nacional.", correta: false },
      { texto: "política externa.", correta: false },
      { texto: "política monetária.", correta: false },
      { texto: "política de defesa nacional.", correta: false },
    ],
    explicacao:
      "A RIDE é instrumento de política de desenvolvimento regional, voltado à integração de serviços e ações entre o DF e os municípios do entorno.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["desenvolvimento regional", "integração"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A relevância da RIDE para a SEDES-DF está em que:",
    alternativas: [
      { texto: "as políticas sociais do DF sofrem impacto da população do entorno que busca serviços na capital.", correta: true },
      { texto: "a RIDE proíbe a atuação da SEDES.", correta: false },
      { texto: "a SEDES administra os municípios de Goiás.", correta: false },
      { texto: "a RIDE não tem relação com políticas sociais.", correta: false },
      { texto: "a SEDES é o órgão gestor federal da RIDE.", correta: false },
    ],
    explicacao:
      "A intensa busca por serviços públicos no DF por moradores do entorno impacta as políticas sociais distritais, tornando a articulação regional relevante para o planejamento da SEDES, ainda que a coordenação da RIDE seja federal.",
    fonteLegal: "Contexto da RIDE; PNAS/2004",
    palavrasChave: ["SEDES", "entorno", "impacto social"],
  },
  {
    assunto: A,
    nivel: "Medio",
    dificuldade: 3,
    enunciado: "A gestão compartilhada de recursos hídricos e meio ambiente na RIDE justifica-se porque:",
    alternativas: [
      { texto: "bacias e recursos naturais não respeitam limites político-administrativos, exigindo ação integrada.", correta: true },
      { texto: "cada município deve isolar seus recursos.", correta: false },
      { texto: "o tema é irrelevante para a região.", correta: false },
      { texto: "a gestão ambiental é vedada na RIDE.", correta: false },
      { texto: "os recursos hídricos pertencem a empresas privadas.", correta: false },
    ],
    explicacao:
      "Recursos hídricos e questões ambientais ultrapassam fronteiras administrativas; por isso, a RIDE favorece a gestão integrada desses temas de interesse comum entre os entes.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["recursos hídricos", "meio ambiente", "gestão integrada"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "Em relação à autonomia dos municípios integrantes, a RIDE:",
    alternativas: [
      { texto: "não suprime a autonomia dos municípios, que permanecem como entes federativos.", correta: true },
      { texto: "extingue a autonomia municipal.", correta: false },
      { texto: "transforma os municípios em distritos do DF.", correta: false },
      { texto: "transfere a administração municipal à União.", correta: false },
      { texto: "dissolve as câmaras municipais.", correta: false },
    ],
    explicacao:
      "A RIDE é um arranjo de articulação que não suprime a autonomia dos municípios; estes permanecem como entes federativos, apenas cooperando em temas de interesse comum.",
    fonteLegal: "CF/1988; Lei Complementar 94/1998",
    palavrasChave: ["autonomia municipal", "cooperação"],
  },
  {
    assunto: A,
    nivel: "Dificil",
    dificuldade: 4,
    enunciado: "A efetividade da RIDE depende, sobretudo, de:",
    alternativas: [
      { texto: "coordenação intergovernamental, planejamento integrado e financiamento das ações comuns.", correta: true },
      { texto: "atuação isolada de cada ente.", correta: false },
      { texto: "ausência de planejamento.", correta: false },
      { texto: "concentração de poder em um único município.", correta: false },
      { texto: "eliminação do financiamento público.", correta: false },
    ],
    explicacao:
      "A efetividade da RIDE depende de forte coordenação intergovernamental, planejamento integrado das políticas e mecanismos de financiamento para viabilizar as ações de interesse comum.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["coordenação", "planejamento", "financiamento"],
  },
  {
    assunto: A,
    nivel: "Facil",
    dificuldade: 2,
    enunciado: "O conceito de 'entorno', associado à RIDE, refere-se a:",
    alternativas: [
      { texto: "municípios próximos ao DF que mantêm forte interdependência com a capital.", correta: true },
      { texto: "bairros internos do Plano Piloto.", correta: false },
      { texto: "estados da região Norte.", correta: false },
      { texto: "países vizinhos do Brasil.", correta: false },
      { texto: "ilhas oceânicas.", correta: false },
    ],
    explicacao:
      "O 'entorno' compreende os municípios próximos ao DF (sobretudo em Goiás) que mantêm intensa interdependência socioeconômica com a capital, integrando a RIDE.",
    fonteLegal: "Lei Complementar 94/1998",
    palavrasChave: ["entorno", "interdependência"],
  },
];

export default questoes;
